import {test,expect} from '@playwright/test';
const key='spritual_website_intention_v1';
test('discover a reflection, pause, finish deliberately, save, return and remove',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/pause/?moment=focus');await expect(page.locator('#pause-reflection')).toContainText('One thing deserves');
 await page.clock.install();await page.getByRole('button',{name:'Begin my pause'}).click();await page.clock.runFor(10000);await expect(page.locator('#time')).toHaveText('0:50');await page.getByRole('button',{name:'Pause timer'}).click();await page.clock.runFor(5000);await expect(page.locator('#time')).toHaveText('0:50');await page.getByRole('button',{name:'Continue my pause'}).click();await page.clock.runFor(50000);await expect(page.locator('#time')).toHaveText('0:00');await expect(page.locator('#finish-view')).toBeHidden();await page.getByRole('button',{name:'Finish my moment'}).click();await expect(page.locator('#finish-heading')).toBeFocused();
 await expect.poll(()=>page.evaluate(k=>localStorage.getItem(k),key)).toBeNull();await page.getByLabel('Listen before I respond').check();await page.getByRole('button',{name:'Keep on this device'}).click();await expect(page.locator('#save-status')).toContainText('kept on this device');await page.reload();await expect(page.locator('#saved-text')).toHaveText('Listen before I respond');await expect(page.locator('#time')).toHaveText('1:00');await page.getByRole('button',{name:'Remove saved intention'}).click();await expect(page.locator('#saved-panel')).toBeHidden();expect(errors).toEqual([]);
});
test('blocked save never claims success and user can continue',async({page})=>{
 await page.addInitScript(()=>{Storage.prototype.setItem=()=>{throw Error('blocked');};});await page.goto('/pause/');await page.locator('#timer-toggle').click();await page.getByRole('button',{name:'Finish my moment'}).click();await page.getByLabel('Give one task my full attention').check();await page.getByRole('button',{name:'Keep on this device'}).click();await expect(page.locator('#save-status')).toContainText('could not save');await expect(page.locator('#saved-panel')).toBeHidden();
});
test('corrupt data requires explicit removal; no accidental overwrite',async({page})=>{
 await page.addInitScript(k=>localStorage.setItem(k,'broken'),key);await page.goto('/pause/');await expect(page.locator('#saved-text')).toContainText('could not be read');await page.locator('#timer-toggle').click();await page.getByRole('button',{name:'Finish my moment'}).click();await expect(page.locator('#save-step')).toBeDisabled();await page.getByRole('button',{name:'Remove saved intention'}).click();await expect(page.locator('#save-step')).toBeEnabled();expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBeNull();
});
test('copy failure has a usable clean link; Hindi keeps language and no saved data',async({page})=>{
 await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw Error('blocked');}}}));await page.goto('/hi/pause/?moment=presence&secret=private');await page.locator('#share-link').click();await expect(page.locator('#copy-url')).toHaveValue(`${process.env.WEBSITE_URL==='https://spritual-co-in.vercel.app'?process.env.WEBSITE_URL:'https://spritual.co.in'}/hi/pause/?moment=presence`);await expect(page.locator('#copy-url')).toBeFocused();await page.getByRole('link',{name:'English',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('lang','en');
});
test('hiding page pauses running time and reset is explicit',async({page})=>{
 await page.goto('/pause/');await page.clock.install();await page.locator('#timer-toggle').click();await page.clock.runFor(8000);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});await expect(page.locator('#timer-status')).toContainText('paused while');await page.clock.runFor(15000);await expect(page.locator('#time')).toHaveText('0:52');await page.locator('#timer-reset').click();await expect(page.locator('#time')).toHaveText('1:00');
});
for(const width of [320,390,768,1440])test(`English and Hindi fit ${width}px; links and images load`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.emulateMedia({reducedMotion:'reduce'});
 for(const path of ['/','/hi/','/pause/','/hi/pause/','/privacy/']){await page.goto(path);await expect(page.locator('h1:visible')).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);for(const img of await page.locator('img:visible').all()){await img.scrollIntoViewIfNeeded();await expect.poll(()=>img.evaluate(i=>(i as HTMLImageElement).complete&&(i as HTMLImageElement).naturalWidth>0)).toBe(true);}}
 await page.goto('/');await page.screenshot({path:`test-results/website-home-${width}.png`,fullPage:true});if(width===390){await page.goto('/hi/');await page.screenshot({path:'test-results/website-hindi-390.png',fullPage:true});await page.goto('/pause/');await page.screenshot({path:'test-results/website-pause-390.png',fullPage:true});}
});
test('static content survives JavaScript off, no app assets or network trackers ship',async({browser,request})=>{
 const context=await browser.newContext({javaScriptEnabled:false,baseURL:process.env.WEBSITE_URL||'http://127.0.0.1:4190'});const page=await context.newPage();await page.goto('/');await expect(page.getByRole('heading',{level:1})).toContainText('Stories to read');await expect(page.getByRole('link',{name:'Browse all stories'})).toHaveAttribute('href','/library/');await page.goto('/story/a-ring-brings-hope/');await expect(page.getByRole('heading',{level:1})).toHaveText('A ring brings hope');await context.close();
 for(const path of ['/alpha/','/art/gita-chariot-cover-v1.webp','/.env','/supabase/']){const response=await request.get(path);expect(response.status()).toBe(404);}
});
test('keyboard skip navigation and 200% text are usable',async({page})=>{
 await page.goto('/');await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'Skip to content'})).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('#main')).toBeFocused();await page.setViewportSize({width:320,height:800});await page.addStyleTag({content:'body{font-size:200%} p,li,button,a{font-size:1em!important}'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
