import {test,expect} from '@playwright/test';
const key='spritual_website_shelf_v1';

test('source directory search, save, language switch and removal remain available',async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('/library/sources/');
 await page.getByLabel('Search books and sections').fill('Sabha');await expect(page.locator('[data-library-row]:visible')).toHaveCount(1);await page.locator('[data-library-row]:visible').click();await expect(page.locator('h1')).toHaveText('Sabha Parva');expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBeNull();
 await page.getByRole('button',{name:'Save this place',exact:true}).click();await expect(page.locator('#shelf-status')).toContainText('Saved on this device');await page.getByRole('link',{name:'हिन्दी',exact:true}).click();await expect(page.getByRole('button',{name:'सहेजा स्थान हटाएँ',exact:true})).toBeVisible();
 await page.goto('/library/saved/');await expect(page.locator('#saved-list')).toContainText('Sabha Parva');await page.reload();await page.locator('#saved-list a').click();await expect(page.locator('h1')).toHaveText('Sabha Parva');await page.getByRole('button',{name:'Remove saved place',exact:true}).click();await page.goto('/library/saved/');await expect(page.locator('#shelf-empty')).toBeVisible();expect(errors).toEqual([]);
});

test('source-directory search combines filters and recovers from an empty result',async({page})=>{
 await page.goto('/library/sources/');await page.getByLabel('Collection',{exact:true}).selectOption('ramayana');await expect(page.locator('[data-library-row]:visible')).toHaveCount(7);await page.getByLabel('Search books and sections').fill('nothing here');await expect(page.locator('#search-empty')).toBeVisible();await page.getByRole('button',{name:'Clear search',exact:true}).click();await expect(page.locator('[data-library-row]')).toHaveCount(32);await expect(page.locator('#search-count')).toContainText('32 results');await expect(page.locator('[data-library-group][open]')).toHaveCount(0);await page.getByLabel('Search books and sections').fill('रुद्र');await expect(page.locator('#search-count')).toContainText('3 results');
});

test('source discovery query and collection survive refresh and language switching',async({page})=>{
 await page.goto('/library/sources/?world=shiva');await page.getByLabel('Collection',{exact:true}).selectOption('shiva');await page.getByLabel('Search books and sections').fill('rudra');await expect(page).toHaveURL(/q=rudra/);await expect(page).toHaveURL(/collection=shiva/);await page.reload();await expect(page.getByLabel('Collection',{exact:true})).toHaveValue('shiva');await expect(page.getByLabel('Search books and sections')).toHaveValue('rudra');await page.getByRole('link',{name:'हिन्दी',exact:true}).click();await expect(page.getByLabel('संग्रह',{exact:true})).toHaveValue('shiva');await expect(page.getByLabel('ग्रन्थ और खण्ड खोजें')).toHaveValue('rudra');await expect(page.locator('html')).toHaveAttribute('data-world','shiva');
});

test('source catalogue exposes collection jumps and readable mobile controls',async({page})=>{
 await page.setViewportSize({width:320,height:760});await page.goto('/library/sources/');await expect(page.locator('.directory-jumps a')).toHaveCount(3);await expect(page.locator('[data-library-group]:visible')).toHaveCount(3);await page.goto('/library/ramayana/sundara/');for(const button of await page.locator('.reader-tools button').all()){const box=await button.boundingBox();expect(box?.height).toBeGreaterThanOrEqual(44);}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

for(const width of [320,390,1440])test(`saved source-guide control keeps readable contrast at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.goto('/library/ramayana/sundara/');const button=page.locator('[data-save]');await expect(button).toHaveText('Save this place');await button.click();await expect(button).toHaveAttribute('aria-pressed','true');await expect(button).toHaveText('Remove saved place');const ratio=await button.evaluate(element=>{const parse=(value:string)=>value.match(/[\d.]+/g)!.slice(0,3).map(Number);const luminance=(rgb:number[])=>rgb.map(value=>{const channel=value/255;return channel<=.03928?channel/12.92:((channel+.055)/1.055)**2.4;}).reduce((sum,value,index)=>sum+value*[.2126,.7152,.0722][index],0);const style=getComputedStyle(element);const foreground=luminance(parse(style.color));const background=luminance(parse(style.backgroundColor));return (Math.max(foreground,background)+.05)/(Math.min(foreground,background)+.05);});expect(ratio).toBeGreaterThanOrEqual(4.5);
});

test('shelf corruption is visible and requires explicit removal',async({page})=>{await page.addInitScript(k=>localStorage.setItem(k,'invalid'),key);await page.goto('/library/ramayana/uttara/');await expect(page.locator('#shelf-warning')).toBeVisible();await expect(page.locator('[data-save]')).toBeDisabled();await page.locator('#clear-shelf').click();await expect(page.locator('[data-save]')).toBeEnabled();expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBeNull();});
test('denied writes do not claim a saved reading place',async({page})=>{await page.addInitScript(()=>{Storage.prototype.setItem=()=>{throw Error('blocked');};});await page.goto('/library/shiva/rudra/');await page.locator('[data-save]').click();await expect(page.locator('#shelf-status')).toContainText('Could not update');await expect(page.locator('[data-save]')).toHaveAttribute('aria-pressed','false');});
test('reading controls, next section, source safety and local-only boundaries',async({page,request})=>{await page.goto('/library/mahabharata/adi/');await expect(page.locator('.editorial-status')).toContainText('unreviewed');await expect(page.locator('.guide-facts li')).toHaveCount(8);await page.getByRole('button',{name:'Larger text',exact:true}).click();await expect(page.locator('#reading-size-status')).toHaveText('110%');await page.getByRole('button',{name:'Focus view',exact:true}).click();await expect(page.locator('body')).toHaveClass(/reading-focus/);const external=page.getByRole('link',{name:'Open source edition',exact:false});await expect(external).toHaveAttribute('href','https://www.gutenberg.org/ebooks/15474');await expect(external).toHaveAttribute('rel','noopener noreferrer');await page.locator('.reader-next a').filter({hasText:'Sabha'}).click();await expect(page.locator('h1')).toHaveText('Sabha Parva');for(const path of ['/sources/pg15474.txt','/library/mahabharata/adi/read/1/','/artifacts/library-source/staged.json'])expect((await request.get(path)).status()).toBe(404);});

for(const width of [320,390,768,1440])test(`story library and source guides fit ${width}px in both languages`,async({page})=>{await page.setViewportSize({width,height:900});await page.emulateMedia({reducedMotion:'reduce'});for(const path of ['/library/','/library/sources/','/library/shiva/','/library/ramayana/uttara/','/hi/library/','/hi/library/sources/','/hi/library/mahabharata/adi/','/hi/library/saved/']){await page.goto(path);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('h1')).toHaveCount(1);}await page.goto('/library/');await page.screenshot({path:`test-results/library-${width}.png`,fullPage:true});});

test('without JavaScript the entire source directory and external links remain usable',async({browser})=>{const context=await browser.newContext({javaScriptEnabled:false,baseURL:process.env.WEBSITE_URL||'http://127.0.0.1:4190'});const page=await context.newPage();await page.goto('/library/sources/');await expect(page.locator('[data-library-row]')).toHaveCount(32);await page.locator('[data-library-row]').filter({hasText:'Uttara Kanda'}).click();await expect(page.getByRole('link',{name:'Open source edition',exact:false})).toHaveAttribute('href','https://www.gutenberg.org/cache/epub/62496/pg62496-images.html');await context.close();});

test('capture current mobile and desktop review states',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});for(const [width,height,name,path] of [[320,760,'library','/library/'],[320,760,'sources','/library/sources/'],[320,760,'guide','/library/ramayana/sundara/'],[320,760,'guide-hi','/hi/library/shiva/vidyeshvara/'],[1440,1000,'library','/library/'],[1440,1000,'guide','/library/ramayana/sundara/'],[390,844,'saved-empty','/library/saved/']] as const){await page.setViewportSize({width,height});await page.goto(path);for(const image of await page.locator('.book-art:visible img').all())await expect.poll(()=>image.evaluate(item=>(item as HTMLImageElement).complete&&(item as HTMLImageElement).naturalWidth>0)).toBe(true);await page.screenshot({path:`test-results/revamp-${name}-${width}.png`,fullPage:true});}});
