import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {collections,allKeys,canPublishBody,releasePolicy} from '../catalog.mjs';
import {guideContent,guideKeys} from '../guide-content.mjs';
import {readShelf,changeShelf,normalizeSearch,SHELF_KEY} from '../library-state.mjs';
const memory=()=>{const map=new Map();return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};};
test('32 stable source guides cover 18 parvas, seven kandas and seven samhitas',()=>{assert.deepEqual(collections.map(x=>x.units.length),[18,7,7]);assert.equal(new Set(allKeys).size,32);for(const c of collections)for(const u of c.units){assert(u.title.en&&u.title.hi);assert.equal(new URL(u.source).protocol,'https:');}assert.match(collections[1].units[6].source,/62496$/);});
test('all 32 guides have distinct bilingual draft orientation and bounded provenance',()=>{assert.deepEqual(guideKeys.sort(),[...allKeys].sort());for(const key of allKeys){const g=guideContent[key];assert.equal(g.kind,'EDITORIAL_EXPLANATION');assert.equal(g.reviewState,'unreviewed');assert.equal(g.sourceRights,'unknown');for(const field of ['overview','figures','themes','reflection']){assert(g[field].en?.length,`${key} ${field}.en`);assert(g[field].hi?.length,`${key} ${field}.hi`);}assert(g.sources.length);for(const source of g.sources)assert.equal(new URL(source.url).protocol,'https:');}assert.equal(new Set(allKeys.map(k=>guideContent[k].overview.en)).size,32);assert.equal(new Set(allKeys.map(k=>guideContent[k].overview.hi)).size,32);});
test('unreliable Ramayana locators retain citations and expose edition-labelled alternates',()=>{for(const key of ['ramayana/bala','ramayana/ayodhya','ramayana/aranya','ramayana/sundara','ramayana/yuddha']){const sources=guideContent[key].sources;assert(sources.some(source=>source.url.includes('valmiki.iitk.ac.in')),`${key} retains IIT citation`);assert(sources.some(source=>source.reference.startsWith('Alternate locator · ')),`${key} has a working alternate`);assert.equal(guideContent[key].reviewState,'unreviewed');assert.equal(guideContent[key].sourceRights,'unknown');}});
test('saved places require an explicit bounded known ID, never a reading history',()=>{const s=memory();assert.equal(readShelf(s,allKeys).kind,'empty');changeShelf(s,allKeys,allKeys[0],true);changeShelf(s,allKeys,allKeys[0],true);assert.deepEqual(readShelf(s,allKeys).items,[allKeys[0]]);assert.deepEqual(JSON.parse(s.getItem(SHELF_KEY)),{version:1,items:[allKeys[0]]});assert.throws(()=>changeShelf(s,allKeys,'private journal',true));changeShelf(s,allKeys,allKeys[0],false);assert.deepEqual(readShelf(s,allKeys).items,[]);});
test('corrupt, unknown, oversized and denied storage are recoverable without overwriting',()=>{const s=memory();for(const value of ['bad',JSON.stringify({version:1,items:['unknown']}),JSON.stringify({version:1,items:Array(33).fill(allKeys[0])})]){s.setItem(SHELF_KEY,value);assert.equal(readShelf(s,allKeys).kind,'invalid');assert.throws(()=>changeShelf(s,allKeys,allKeys[0],true));assert.equal(s.getItem(SHELF_KEY),value);}assert.throws(()=>changeShelf({getItem:()=>null,setItem:()=>{throw Error('denied');}},allKeys,allKeys[0],true));});
test('search normalizes accents without stripping Hindi marks',()=>{assert.equal(normalizeSearch('Śiva'),'siva');assert.equal(normalizeSearch('  सभा '),'सभा');assert.equal(normalizeSearch('a'.repeat(140)).length,120);});
test('publication and paid access remain fail-closed',()=>{const record={version:2,rights:{status:'cleared',evidence:'test-only',territories:'worldwide'},review:{status:'approved',reviewer:'test reviewer',version:2},access:'free'};assert.equal(canPublishBody(record),true);for(const change of [{access:'paid'},{review:{...record.review,version:1}},{rights:{...record.rights,status:'unverified'}}])assert.equal(Boolean(canPublishBody({...record,...change})),false);assert.equal(Boolean(canPublishBody({})),false);assert.equal(releasePolicy.paidAccessEnabled,false);assert.equal(releasePolicy.price,null);});
test('public build emits reviewed original stories but never imported religious prose',async()=>{const root=new URL('../dist/',import.meta.url);const files=await readdir(root,{recursive:true});assert(files.includes('read/a-ring-brings-hope/index.html'));assert(files.includes('story/a-ring-brings-hope/index.html'));assert(files.includes('corrections/index.html'));assert(!files.some(f=>f.startsWith('sources/')||f.includes('staged.json')));for(const file of files.filter(f=>f.endsWith('.html'))){const html=await readFile(new URL(file,root),'utf8');assert(!html.includes('LOCAL EDITORIAL PREVIEW'));assert(!html.includes('LOCAL SANATAN RELEASE PREVIEW'));assert(!html.includes('Vaishampayana said,'));}const detail=await readFile(new URL('story/a-ring-brings-hope/index.html',root),'utf8');const reader=await readFile(new URL('read/a-ring-brings-hope/index.html',root),'utf8');const corrections=await readFile(new URL('corrections/index.html',root),'utf8');assert(detail.includes('index, follow'));assert(reader.includes('noindex, follow'));assert(corrections.includes('https://github.com/abhijay-sudo/spritual/issues/new'));const guarded=spawnSync(process.execPath,['website/build.mjs','--editorial-preview'],{cwd:new URL('../../',import.meta.url),env:{...process.env,CI:'true'},encoding:'utf8'});assert.notEqual(guarded.status,0);assert.match(guarded.stderr,/local only/);});
test('public guides render the draft boundary, exact content, art and SVG interaction icons',async()=>{const root=new URL('../dist/',import.meta.url);for(const key of allKeys){for(const prefix of ['','hi/']){const html=await readFile(new URL(`${prefix}library/${key}/index.html`,root),'utf8');assert(html.includes(prefix?'प्रारूप परिचय':'DRAFT ORIENTATION'));assert(html.includes(guideContent[key].overview[prefix?'hi':'en']));assert(!html.includes('Before you begin'));assert(!html.includes('aria-hidden="true">↗'));}}for(const id of ['mahabharata','ramayana','shiva']){const asset=await readFile(new URL(`assets/collection-${id}.webp`,root));assert(asset.byteLength>100000);}const home=await readFile(new URL('index.html',root),'utf8');assert(!home.includes('aria-hidden="true">↗'));});
test('every library page has a unique title, working internal links and matching language',async()=>{
 const root=new URL('../dist/',import.meta.url);
 const files=await readdir(root,{recursive:true});
 const pages=files.filter(f=>f.endsWith('index.html')&&(f.startsWith('library/')||f.startsWith('hi/library/')));
 assert.equal(pages.length,74);
 const titles=new Set();
 for(const file of pages){
  const html=await readFile(new URL(file,root),'utf8');
  assert(html.includes(`<html lang="${file.startsWith('hi/')?'hi':'en'}">`));
  const title=html.match(/<title>(.*?)<\/title>/)[1];assert(!titles.has(title),`Duplicate ${title}`);titles.add(title);
  if(file.includes('/saved/'))assert(html.includes('noindex, follow'));
  for(const [,href] of html.matchAll(/href="(\/[^"?#]*)"/g)){
   const target=href.endsWith('/')?`${href.slice(1)}index.html`:href.slice(1);
   assert(files.includes(target),`${file} links to missing ${target}`);
  }
 }
});
