import test from 'node:test';
import assert from 'node:assert/strict';
import {READING_KEY,emptyReadingState,readReadingState,saveProgress,setPreference,setOnboarding,toggleBookmark,removeProgress,removeBookmark,restoreRemovedReadingItem,resolveProgress} from '../reading-state.mjs';

const allowed=['story-one','story-two'];
const memory=initial=>{const values=new Map(Object.entries(initial||{}));return {getItem:key=>values.has(key)?values.get(key):null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key),value:key=>values.get(key)};};
const progress={storyId:'story-one',contentRevision:'rev-1',language:'en',sceneId:'scene-one',blockId:'block-one',blockOffsetRatio:.4,updatedAt:100};

test('reading state saves preferences, progress and typed bookmarks',()=>{const store=memory();saveProgress(store,allowed,progress);setPreference(store,allowed,'theme','sepia');setOnboarding(store,allowed,'skipped');toggleBookmark(store,allowed,{storyId:'story-one',sceneId:'scene-one',blockId:'block-one',language:'en',kind:'place',createdAt:101});const result=readReadingState(store,allowed);assert.equal(result.kind,'ready');assert.equal(result.state.preferences.theme,'sepia');assert.equal(result.state.progress['story-one'].blockOffsetRatio,.4);assert.equal(result.state.bookmarks[0].kind,'place');assert.equal(result.state.onboarding,'skipped');});
test('corrupt records fail closed and are not overwritten',()=>{const store=memory({[READING_KEY]:'broken'});assert.equal(readReadingState(store,allowed).kind,'invalid');assert.throws(()=>setPreference(store,allowed,'theme','dark'),/Unreadable/);assert.equal(store.value(READING_KEY),'broken');const malformed=emptyReadingState();malformed.progress['story-one']={...progress,blockOffsetRatio:4};store.setItem(READING_KEY,JSON.stringify(malformed));assert.equal(readReadingState(store,allowed).kind,'invalid');});
test('removing resume progress preserves bookmarks and revision changes fall back safely',()=>{const store=memory();saveProgress(store,allowed,progress);toggleBookmark(store,allowed,{storyId:'story-one',sceneId:'scene-one',blockId:'block-one',language:'en',createdAt:101});removeProgress(store,allowed,'story-one');const result=readReadingState(store,allowed);assert.equal(result.state.progress['story-one'],undefined);assert.equal(result.state.bookmarks.length,1);const resolved=resolveProgress(progress,{id:'story-one',contentRevision:'rev-2',scenes:[{id:'scene-one',blocks:[{id:'block-one'}]}]});assert.equal(resolved.revisionChanged,true);assert.equal(resolved.ratio,0);});
test('unknown bookmark kinds fail closed while legacy untyped bookmarks remain readable',()=>{const store=memory();toggleBookmark(store,allowed,{storyId:'story-one',sceneId:'scene-one',blockId:'block-one',language:'en',createdAt:101});assert.equal(readReadingState(store,allowed).kind,'ready');const state=readReadingState(store,allowed).state;state.bookmarks[0].kind='unknown';store.setItem(READING_KEY,JSON.stringify(state));assert.equal(readReadingState(store,allowed).kind,'invalid');});

test('bookmark insertion stays readable at the one-hundred item boundary',()=>{const store=memory();for(let index=0;index<101;index++)toggleBookmark(store,allowed,{storyId:'story-one',sceneId:'scene-one',blockId:`block-${index}`,language:'en',kind:'place',createdAt:1000+index});const result=readReadingState(store,allowed);assert.equal(result.kind,'ready');assert.equal(result.state.bookmarks.length,100);assert.equal(result.state.bookmarks[0].blockId,'block-100');assert.equal(result.state.bookmarks.at(-1).blockId,'block-1');});

test('story saves and first-paragraph place saves have distinct identities',()=>{const store=memory(),base={storyId:'story-one',sceneId:'scene-one',blockId:'block-one',language:'en'};toggleBookmark(store,allowed,{...base,kind:'story',createdAt:101});toggleBookmark(store,allowed,{...base,kind:'place',createdAt:102});let result=readReadingState(store,allowed);assert.deepEqual(result.state.bookmarks.map(item=>item.kind),['place','story']);toggleBookmark(store,allowed,{...base,kind:'story',createdAt:103});result=readReadingState(store,allowed);assert.deepEqual(result.state.bookmarks.map(item=>item.kind),['place']);});

test('retired catalogue items are dropped without invalidating active reading data',()=>{const state=emptyReadingState();state.preferences.theme='sepia';state.progress['story-one']=progress;state.progress.retired={...progress,storyId:'retired'};state.bookmarks=[{storyId:'retired',sceneId:'old-scene',blockId:'old-block',language:'en',kind:'place',createdAt:90},{storyId:'story-one',sceneId:'scene-one',blockId:'block-one',language:'en',kind:'place',createdAt:101}];const store=memory({[READING_KEY]:JSON.stringify(state)});const result=readReadingState(store,allowed);assert.equal(result.kind,'ready');assert.equal(result.recovered,true);assert.equal(result.state.preferences.theme,'sepia');assert.deepEqual(Object.keys(result.state.progress),['story-one']);assert.deepEqual(result.state.bookmarks.map(item=>item.storyId),['story-one']);});

test('targeted undo preserves newer preferences and progress from another tab',()=>{const store=memory();saveProgress(store,allowed,progress);setPreference(store,allowed,'theme','sepia');removeProgress(store,allowed,'story-one');setPreference(store,allowed,'theme','dark');saveProgress(store,allowed,{...progress,blockId:'block-two',blockOffsetRatio:.8,updatedAt:200});restoreRemovedReadingItem(store,allowed,{type:'progress',item:progress});const result=readReadingState(store,allowed);assert.equal(result.state.preferences.theme,'dark');assert.equal(result.state.progress['story-one'].blockId,'block-two');assert.equal(result.state.progress['story-one'].updatedAt,200);});

test('targeted bookmark undo restores only the removed item',()=>{const store=memory(),removed={storyId:'story-one',sceneId:'scene-one',blockId:'block-one',language:'en',kind:'place',createdAt:101},newer={storyId:'story-two',sceneId:'scene-two',blockId:'block-two',language:'en',kind:'story',createdAt:202};toggleBookmark(store,allowed,removed);removeBookmark(store,allowed,removed);toggleBookmark(store,allowed,newer);setPreference(store,allowed,'textSize',24);restoreRemovedReadingItem(store,allowed,{type:'bookmark',item:removed});const result=readReadingState(store,allowed);assert.equal(result.state.preferences.textSize,24);assert.deepEqual(result.state.bookmarks.map(item=>item.storyId),['story-one','story-two']);});
