import test from 'node:test';
import assert from 'node:assert/strict';
import {READING_KEY,emptyReadingState,readReadingState,saveProgress,setPreference,setOnboarding,toggleBookmark,removeProgress,resolveProgress} from '../reading-state.mjs';

const allowed=['story-one','story-two'];
const memory=initial=>{const values=new Map(Object.entries(initial||{}));return {getItem:key=>values.has(key)?values.get(key):null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key),value:key=>values.get(key)};};
const progress={storyId:'story-one',contentRevision:'rev-1',language:'en',sceneId:'scene-one',blockId:'block-one',blockOffsetRatio:.4,updatedAt:100};

test('reading state saves preferences, progress and typed bookmarks',()=>{const store=memory();saveProgress(store,allowed,progress);setPreference(store,allowed,'theme','sepia');setOnboarding(store,allowed,'skipped');toggleBookmark(store,allowed,{storyId:'story-one',sceneId:'scene-one',blockId:'block-one',language:'en',kind:'place',createdAt:101});const result=readReadingState(store,allowed);assert.equal(result.kind,'ready');assert.equal(result.state.preferences.theme,'sepia');assert.equal(result.state.progress['story-one'].blockOffsetRatio,.4);assert.equal(result.state.bookmarks[0].kind,'place');assert.equal(result.state.onboarding,'skipped');});
test('corrupt or unknown records fail closed and are not overwritten',()=>{const store=memory({[READING_KEY]:'broken'});assert.equal(readReadingState(store,allowed).kind,'invalid');assert.throws(()=>setPreference(store,allowed,'theme','dark'),/Unreadable/);assert.equal(store.value(READING_KEY),'broken');const unknown=emptyReadingState();unknown.progress.bad={...progress,storyId:'bad'};store.setItem(READING_KEY,JSON.stringify(unknown));assert.equal(readReadingState(store,allowed).kind,'invalid');});
test('removing resume progress preserves bookmarks and revision changes fall back safely',()=>{const store=memory();saveProgress(store,allowed,progress);toggleBookmark(store,allowed,{storyId:'story-one',sceneId:'scene-one',blockId:'block-one',language:'en',createdAt:101});removeProgress(store,allowed,'story-one');const result=readReadingState(store,allowed);assert.equal(result.state.progress['story-one'],undefined);assert.equal(result.state.bookmarks.length,1);const resolved=resolveProgress(progress,{id:'story-one',contentRevision:'rev-2',scenes:[{id:'scene-one',blocks:[{id:'block-one'}]}]});assert.equal(resolved.revisionChanged,true);assert.equal(resolved.ratio,0);});
test('unknown bookmark kinds fail closed while legacy untyped bookmarks remain readable',()=>{const store=memory();toggleBookmark(store,allowed,{storyId:'story-one',sceneId:'scene-one',blockId:'block-one',language:'en',createdAt:101});assert.equal(readReadingState(store,allowed).kind,'ready');const state=readReadingState(store,allowed).state;state.bookmarks[0].kind='unknown';store.setItem(READING_KEY,JSON.stringify(state));assert.equal(readReadingState(store,allowed).kind,'invalid');});
