// Research import only. Never a publication or rights approval.
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {collections} from '../catalog.mjs';
const dir=resolve(import.meta.dirname,'../../artifacts/library-source');await mkdir(dir,{recursive:true});
const hashes=[],units={};
async function source(id){const path=`${dir}/pg${id}.txt`;let text;try{text=await readFile(path,'utf8');}catch{const r=await fetch(`https://www.gutenberg.org/cache/epub/${id}/pg${id}.txt`);if(!r.ok)throw Error(`Source ${id}: ${r.status}`);text=await r.text();if(!text.includes('START OF THE PROJECT GUTENBERG'))throw Error('Unexpected source response');await writeFile(path,text);}
 hashes.push({id,url:`https://www.gutenberg.org/ebooks/${id}`,sha256:createHash('sha256').update(text).digest('hex'),bytes:Buffer.byteLength(text)});return text.replaceAll('\r\n','\n').split(/\*\*\* END OF (?:THE|THIS) PROJECT GUTENBERG/)[0];}
for(const id of [15474,15475,15476,15477]){const t=await source(id);const books=[...t.matchAll(/^BOOK (\d+)\s*$/gm)];for(let i=0;i<books.length;i++){const n=Number(books[i][1]);const body=t.slice(books[i].index+books[i][0].length,books[i+1]?.index);const numbered=[8,9,10,11,16,17,18].includes(n);const re=numbered?/^\d+\s*$/gm:/^SECTION [IVXLCDM]+[^\n]*$/gm;const sections=[...body.matchAll(re)];if(!sections.length)throw Error(`No chapters book ${n}`);const chapters=sections.map((m,j)=>({id:String(j+1),title:m[0].trim(),text:body.slice(m.index+m[0].length,sections[j+1]?.index).trim()}));const unit=collections[0].units[n-1];units[`mahabharata/${unit.id}`]={sourceId:id,kind:'historical-translation',introduction:body.slice(0,sections[0].index).trim(),chapters};}}
for(const [id,names] of [[57265,[['bala',/^BALAKANDAM\.[ \t]*$/gm],['ayodhya',/^AYODHYAKANDAM[ \t]*$/gm]]],[57826,[['aranya',/^ARANYA KANDAM\.[ \t]*$/gm],['kishkindha',/^KISHKINDHA KANDAM\.[ \t]*$/gm],['sundara',/^SUNDARA KANDAM\.[ \t]*$/gm]]],[60188,[['yuddha',/^SECTION I\.[ \t]*$/gm]]],[62496,[['uttara',/^UTTARAKĀNDAM[ \t]*$/gm]]]]){
 const text=await source(id);const starts=names.map(([name,re])=>{const hit=[...text.matchAll(re)].at(-1);if(!hit)throw Error(`Missing ${name} heading`);return {name,index:hit.index};});
 for(let i=0;i<starts.length;i++){const body=text.slice(starts[i].index,starts[i+1]?.index);const heads=[...body.matchAll(/^SECTION [IVXLCDM]+\.?[ \t]*$/gm)];if(!heads.length)throw Error(`No sections ${starts[i].name}`);units[`ramayana/${starts[i].name}`]={sourceId:id,kind:'historical-translation',introduction:body.slice(0,heads[0].index).trim(),chapters:heads.map((m,j)=>({id:String(j+1),title:m[0].trim(),text:body.slice(m.index+m[0].length,heads[j+1]?.index).trim()}))};}
}
const staged={version:1,rights:{status:'unverified',territories:null,evidence:null},review:{status:'pending',reviewer:null},access:'not-published',language:'en',sources:hashes,units};
await writeFile(`${dir}/staged.json`,JSON.stringify(staged));
const report={sources:hashes,books:Object.entries(units).map(([id,u])=>({id,sections:u.chapters.length,characters:u.chapters.reduce((n,c)=>n+c.text.length,0),kind:u.kind})),limitations:['Not proofread against scans','No named editorial approval','No worldwide/commercial rights clearance','No Hindi translation','Source numbering can contain duplicates or gaps; not silently repaired','No Shiva translation imported: rights unresolved']};await writeFile(`${dir}/import-report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
