import { mkdir, readFile, writeFile, copyFile, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { copy } from './content.mjs';
import {collections} from './catalog.mjs';
import {libraryHome,collectionPage,richUnitPage,savedPage,libraryTeaser,editorialReader} from './library-views.mjs';
import {stories,storyById,characters,pick} from './stories.mjs';
import {storyHome,storyLibrary,storyDetail,storyReader,characterPage,dailyPage,myReadingPage,storyPrivacy,correctionsPage,storyGeneratedRoutes,storySitemapRoutes} from './story-views.mjs';
const editorial=process.argv.includes('--editorial-preview');
const sanatanPreview=process.argv.includes('--sanatan-preview');
const sanatan=!editorial;
if(editorial&&(process.env.VERCEL||process.env.CI))throw Error('Editorial source previews are local only.');
if(sanatanPreview&&(process.env.VERCEL||process.env.CI))throw Error('Sanatan release previews are local only.');
if(editorial&&sanatanPreview)throw Error('Choose one local preview mode.');
const out=resolve(import.meta.dirname,editorial?'../artifacts/editorial-site':sanatanPreview?'../artifacts/sanatan-site':'dist');
const staged=editorial?JSON.parse(await readFile(resolve(import.meta.dirname,'../artifacts/library-source/staged.json'),'utf8')):null;
await rm(out,{recursive:true,force:true}); await mkdir(out,{recursive:true}); await mkdir(`${out}/assets`);
// Deliberate allowlist: the local app's content, artwork, auth and fixture bundle are never deployed here.
for(const file of ['brand.svg','landscape.svg','fraunces-latin.woff2','anek-devanagari.woff2','tiro-devanagari-sanskrit.woff2','OFL-Fraunces.txt','OFL-Anek-Devanagari.txt','OFL-Tiro-Devanagari-Sanskrit.txt','collection-mahabharata.webp','collection-mahabharata-sm.webp','collection-ramayana.webp','collection-ramayana-sm.webp','collection-shiva.webp','collection-shiva-sm.webp','world-rama.webp','world-krishna.webp','world-hanuman.webp','world-shiva.webp']) await copyFile(resolve(import.meta.dirname,'assets',file),`${out}/assets/${file}`);
for(const file of ['site.css','site.js','theme-init.js','session.mjs','library.css','library.js','library-state.mjs']) await copyFile(resolve(import.meta.dirname,file),`${out}/${file.endsWith('.mjs') ? file.replace('.mjs','.js') : file}`);
if(sanatan)for(const file of ['reading.css','reading.js','reading-state.mjs']) await copyFile(resolve(import.meta.dirname,file),`${out}/${file.endsWith('.mjs') ? file.replace('.mjs','.js') : file}`);
const arrow='<svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const arrowBack='<svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M20 12H5m6-6-6 6 6 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const arrowOut='<svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M8 16 17 7M10 7h7v7" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const arrowDown='<svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M12 4v15m-6-6 6 6 6-6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const play='<svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="m9 6 9 6-9 6V6Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/></svg>';
const sun='<svg aria-hidden="true" viewBox="0 0 64 64" fill="none"><g stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><path d="M9 43h46M18 36a14 14 0 0 1 28 0M32 7v9M9 17l7 7M55 17l-7 7M10 52h44"/></g></svg>';
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const worlds=[
 {id:'neutral',en:'Still',hi:'शांत',mark:'○'},
 {id:'epic',en:sanatan?'Epic':'Mahabharata',hi:sanatan?'महाकाव्य':'महाभारत',mark:sanatan?'क':'18'},
 {id:'rama',en:'Rama',hi:'राम',mark:'रा'},
 {id:'krishna',en:'Krishna',hi:'कृष्ण',mark:'कृ'},
 {id:'hanuman',en:'Hanuman',hi:'हनुमान',mark:'ह'},
 {id:'shiva',en:'Shiva',hi:'शिव',mark:'शि'}
];
function routeWorld(route){
 const storyId=route.match(/^(?:story|read)\/([^/]+)\//)?.[1];
 if(storyId&&storyById[storyId])return storyById[storyId].world;
 const characterId=route.match(/^characters\/([^/]+)\//)?.[1];
 if(characterId&&characters[characterId])return characters[characterId].world;
 if(route.startsWith('library/shiva/'))return 'shiva';
 if(route.startsWith('library/ramayana/kishkindha/')||route.startsWith('library/ramayana/sundara/'))return 'hanuman';
 if(route.startsWith('library/ramayana/'))return 'rama';
 if(route.startsWith('library/mahabharata/'))return 'epic';
 return 'neutral';
}
function worldChooser(lang,route){
 const hi=lang==='hi',path=`${hi?'/hi/':'/'}${route}`;
 return `<section class="world-bar" aria-labelledby="world-label"><div class="wrap world-bar-inner"><div class="world-prompt"><span class="world-orbit" aria-hidden="true"></span><span id="world-label">${hi?'अपना दृश्य संसार चुनें':'Choose a visual world'}</span></div><nav class="world-options" aria-label="${hi?'दृश्य संसार':'Visual world'}">${worlds.map(w=>`<a href="${path}?world=${w.id}" data-world-option="${w.id}"><span aria-hidden="true">${w.mark}</span>${hi?w.hi:w.en}</a>`).join('')}</nav><p id="world-status" class="sr-only" role="status"></p></div></section>`;
}
function header(c,lang,route){
 const base=lang==='hi'?'/hi/':'/';const hi=lang==='hi';const ritual=route==='pause/';
 const labels=sanatan?(hi?['कथाएँ','आज','शांत पल','मेरा पठन']:['Stories','Today','Quiet moment','My reading']):(hi?['पुस्तकालय','शांत पल','दृष्टिकोण','सवाल','सहेजे स्थान']:['Library','Quiet moment','Approach','Questions','Saved places']);
 const targets=sanatan?['library/','daily/','pause/','my-reading/']:['library/','pause/','#approach','#questions','library/saved/'];
 const links=labels.map((label,i)=>`<a href="${base}${targets[i]}" ${route===targets[i]?'aria-current="page"':''}>${label}</a>`);
 const language=`<div class="language-pair" aria-label="${hi?'भाषा':'Language'}">${hi?`<a class="language" href="/${route}" lang="en" aria-label="English">EN</a><span aria-current="true" lang="hi">हिन्दी</span>`:`<span aria-current="true" lang="en">EN</span><a class="language" href="/hi/${route}" lang="hi">हिन्दी</a>`}</div>`;
 return `<a class="skip" href="#main">${c.skip}</a><header class="header wrap ${ritual?'ritual-header':''}"><a class="brand" href="${base}" aria-label="Spritual ${hi?'मुखपृष्ठ':'home'}"><img src="/assets/brand.svg" width="36" height="36" alt=""/><span>Spritual<span class="brand-dot">.</span></span></a>${ritual?'':`<nav class="desktop-nav" aria-label="${hi?'मुख्य नेविगेशन':'Main navigation'}">${links.slice(0,sanatan?4:3).join('')}</nav>`}<div class="header-actions">${language}${ritual?`<a class="ritual-close text-link" href="${base}">${hi?'बंद करें':'Close'} <span aria-hidden="true">×</span></a>`:`<button class="menu-toggle" id="menu-toggle" aria-expanded="false" aria-controls="mobile-menu" hidden>${hi?'मेनू':'Menu'} <span aria-hidden="true">☰</span></button>`}</div></header>${ritual?'':`<dialog id="mobile-menu" aria-labelledby="menu-title"><div class="menu-sheet"><div class="menu-top"><h2 id="menu-title">${hi?'अपना रास्ता चुनें।':'Find your own way.'}</h2><button id="menu-close" class="text-button">${hi?'बंद करें':'Close'} ×</button></div><nav aria-label="${hi?'मोबाइल नेविगेशन':'Mobile navigation'}">${links.join('')}</nav><p class="fine">${c.status}</p></div></dialog><noscript><nav class="nojs-nav wrap" aria-label="${hi?'नेविगेशन':'Navigation'}">${links.join('')}</nav></noscript>`}${worldChooser(lang,route)}${route.startsWith('library/')&&!(sanatan&&(route==='library/'||route==='library/saved/'))?`<nav class="library-subnav wrap" aria-label="${hi?'पठन नेविगेशन':'Reading navigation'}">${collections.map(x=>`<a href="${base}library/${x.id}/" ${route.startsWith('library/'+x.id+'/')?'aria-current="page"':''}>${x.id==='shiva'?(hi?'शिव':'Shiva'):x.title[lang]}</a>`).join('')}<a href="${base}library/saved/" ${route==='library/saved/'?'aria-current="page"':''}>${hi?'सहेजे स्थान':'Saved'}</a></nav>`:''}`;
}
function footer(c,lang){let b=lang==='hi'?'/hi/':'/';return `<footer class="footer wrap"><div><a class="brand" href="${b}"><img src="/assets/brand.svg" width="36" height="36" alt=""/><span>Spritual.</span></a><p>${sanatan?(lang==='hi'?'निःशुल्क, स्रोत-सजग कथाएँ। अपनी गति से पढ़ें।':'Free, source-aware stories. Read at your own pace.'):c.footerLine}</p></div><nav class="footer-links" aria-label="${lang==='hi'?'पादलेख':'Footer'}"><a href="${b}library/">${lang==='hi'?'पुस्तकालय':'Library'}</a>${sanatan?`<a href="${b}daily/">${lang==='hi'?'आज':'Today'}</a><a href="${b}my-reading/">${lang==='hi'?'मेरा पठन':'My reading'}</a><a href="${b}corrections/">${lang==='hi'?'सुधार':'Corrections'}</a>`:`<a href="${b}pause/">${c.pauseTitle}</a>`}<a href="${b}privacy/">${c.privacy}</a><span>© 2026 Spritual</span></nav><p class="footer-note">${sanatan?(lang==='hi'?'मौलिक पुनर्कथन; शास्त्र-पाठ या अनुवाद नहीं। मालिक के अभिलेख में पूजा भगत की समीक्षा दर्ज है; योग्यता उपलब्ध नहीं कराई गई।':'Original retellings, not scripture text or translations. The owner records review by Puja Bhagat; credentials were not supplied.'):c.footerNote}</p></footer>`;}
function home(c,lang){const b=lang==='hi'?'/hi/':'/';const hi=lang==='hi';return `<main id="main">
<section class="hero wrap"><div class="hero-copy" data-enter><p class="eyebrow">${c.eyebrow}</p><h1>${c.hero}</h1><p class="hero-intro">${c.intro}</p><div class="hero-actions"><a class="button" href="${b}pause/">${c.pauseTitle}${arrow}</a><a class="button outline" href="${b}library/">${hi?'पुस्तकालय में आएँ':'Enter the library'}${arrow}</a></div><a id="home-continue" class="home-continue text-link" hidden>${hi?'सहेजी मार्गदर्शिका जारी रखें':'Continue your saved guide'}${arrow}</a><p class="fine">${c.free}</p></div><div class="hero-visual" data-enter><div class="arch-frame"><img class="landscape" data-context-art src="/assets/landscape.svg" width="900" height="1120" fetchpriority="high" alt=""/><div class="art-caption"><span class="eyebrow" data-context-kicker>${c.artLabel}</span><p data-context-caption>${c.artTitle}</p></div></div><div class="orbit-seal" aria-hidden="true">${sun}<span data-context-seal>STILLNESS<br>WITHIN</span></div></div><div class="trust">${(hi?['60 सेकंड का शांत पल','English और हिन्दी','अपनी गति, बिना स्ट्रीक']:['Stillness in 60 seconds','English & हिन्दी','Your pace, no streaks']).map(x=>`<span>${x}</span>`).join('')}</div></section>
${iconizeLibrary(libraryTeaser(lang))}
<section class="section wrap" id="experience"><div class="section-heading"><h2>${hi?'Spritual का तरीका':'The Spritual way'}</h2><p class="section-intro">${c.experienceIntro}</p></div><div class="pillars">${c.pillars.map((p,i)=>`<article class="pillar reveal"><span class="number">0${i+1}</span><h3>${p[0]}</h3><p>${p[1]}</p><span class="eyebrow pillar-caption">${p[2]}</span></article>`).join('')}</div><p class="development-note">${c.develop}</p></section>
<section class="moments"><div class="wrap moments-grid"><div><p class="eyebrow">${c.momentsLabel}</p><h2>${c.momentsTitle}</h2><p>${c.momentsIntro}</p><div class="moment-tabs" role="group" aria-label="${c.momentsLabel}"><span class="moment-indicator" aria-hidden="true"></span>${c.moments.map((m,i)=>`<button type="button" data-moment="${i}" aria-pressed="${i===0}">${m[0]}${arrowOut}</button>`).join('')}</div></div><div class="reflection-card reveal" data-mood="stillness"><div class="reflection-top"><span class="eyebrow">${c.sample}</span>${sun}</div><div id="moment-copy" aria-live="polite"><h3>${c.moments[0][1]}</h3><p>${c.moments[0][2]}</p></div><a id="moment-link" class="button" href="${b}pause/?moment=stillness">${c.momentAction}${arrow}</a><span class="fine">${c.momentNote}</span></div></div></section>
<section class="philosophy" id="approach"><div class="wrap philosophy-grid"><div><p class="eyebrow">${c.philosophyLabel}</p><h2>${c.philosophy}</h2><div class="principles">${c.principles.map((p,i)=>`<div class="reveal"><span aria-hidden="true">0${i+1}</span><h3>${p[0]}</h3><p>${p[1]}</p></div>`).join('')}</div></div><div class="app-well" id="app"><div class="device-preview" aria-label="${hi?'वेबसाइट के शांत पल का चित्र':'Illustration of the website quiet moment'}"><p class="eyebrow">Spritual</p><h3>${c.pauseTitle}</h3><div class="preview-dial" aria-hidden="true">1:00</div><p>${c.silence}</p></div><p class="ready-caption">${hi?'इस वेबसाइट पर उपलब्ध।':'Ready on this website.'}</p><div class="future-app"><p><span class="status-dot"></span>${c.appStatus}</p><ul>${c.appPoints.map(x=>`<li>${x}</li>`).join('')}</ul><p class="fine">${c.appNote}</p></div></div></div></section>
<section class="faq wrap section" id="questions"><div><p class="eyebrow">${c.nav[2]}</p><h2>${c.faqTitle}</h2></div><div>${c.faqs.map(f=>`<details><summary>${f[0]}<span aria-hidden="true">+</span></summary><div class="faq-answer"><p>${f[1]}</p></div></details>`).join('')}</div><div class="close-line"><p>${c.finalText}</p><a class="text-link" href="${b}pause/">${c.pauseTitle}${arrow}</a></div></section></main>`;}
function pause(c,lang){let b=lang==='hi'?'/hi/':'/';return `<main id="main" class="pause-main wrap"><div class="pause-layout"><aside class="pause-art"><img data-context-art src="/assets/landscape.svg" width="900" height="1120" alt=""/><div><p class="eyebrow">${c.sample}</p><h2 id="pause-reflection">${c.moments[0][1]}</h2></div></aside><div class="pause-content"><section id="timer-view"><p class="eyebrow">${c.pauseTag}</p><h1>${c.pauseTitle}</h1><p>${c.pauseIntro}</p><div class="timer-dial" id="timer-dial"><svg viewBox="0 0 220 220" aria-hidden="true"><circle cx="110" cy="110" r="102"/><circle id="timer-progress" cx="110" cy="110" r="102" pathLength="60"/></svg><div><span id="time" role="timer" aria-label="${c.remaining}">1:00</span><span>${c.remaining}</span></div></div><p class="timer-status" id="timer-status" role="status">${c.ready}</p><div class="timer-controls"><button id="timer-toggle" class="button">${play}${c.start}</button><button id="timer-reset" class="text-button" hidden>${c.reset}</button></div><button id="finish" class="text-button finish-button" hidden>${c.finish}${arrow}</button><p class="fine">${c.silence}</p></section>
<section id="finish-view" hidden><p class="eyebrow">${c.finalLabel}</p><h1 tabindex="-1" id="finish-heading">${c.finishTitle}</h1><p>${c.finishText}</p><fieldset><legend>${c.stepLabel}</legend>${c.steps.map((s,i)=>`<label class="step-option"><input type="radio" name="intention" value="${i}"/><span>${s}</span></label>`).join('')}</fieldset><button class="button" id="save-step">${c.save}${arrow}</button><p class="fine">${c.savingNote}</p><p id="save-status" role="status"></p><a id="return-reading" class="text-link" hidden>${lang==='hi'?'अपनी मार्गदर्शिका पर लौटें':'Return to your guide'}${arrow}</a><a class="text-link" href="${b}">${c.finishNoSave}${arrow}</a><a class="text-link" href="${b}library/">${lang==='hi'?'पुस्तकालय खोलें':'Open the library'}${arrow}</a></section>
<section id="saved-panel" class="saved-panel" hidden><p class="eyebrow">${c.savedHeading}</p><p id="saved-text"></p><button class="text-button" id="remove-step">${c.remove}</button><p id="remove-status" role="status"></p></section><div class="share-area"><button class="text-button" id="share-link">${c.share}${arrow}</button><p id="share-status" role="status"></p><label id="copy-fallback" hidden>${c.copyError}<input id="copy-url" readonly type="url"/></label></div><noscript><p class="notice">${c.noJS}</p></noscript></div></div></main>`;}
function privacy(c,lang){let b=lang==='hi'?'/hi/':'/';return `<main class="legal wrap" id="main"><a class="text-link" href="${b}">${arrowBack}${c.back}</a><p class="eyebrow">${c.privacy}</p><h1>${c.privacyTitle}</h1><p class="lead">${c.privacyIntro}</p>${c.privacySections.map((p,i)=>`<section><h2>${p[0]}</h2><p>${p[1]}</p>${i===2?`<a class="text-link" href="https://vercel.com/legal/privacy-policy" rel="noreferrer">Vercel Privacy Notice${arrowOut}</a>`:''}</section>`).join('')}<a class="button" href="${b}pause/">${c.savedHeading}${arrow}</a></main>`;}
function page(c,lang,route,body,noindex=false,customTitle=null,customDescription=null){let url=`https://spritual.co.in/${lang==='hi'?'hi/':''}${route}`;let title=customTitle|| (route==='pause/'?`${c.pauseTitle} — Spritual`:route==='privacy/'?`${c.privacy} — Spritual`:c.title),description=customDescription||c.description;const context=routeWorld(route),quiet=route.startsWith('read/');return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>${title}</title><meta name="description" content="${esc(description)}"/><meta name="theme-color" content="#fff9f0"/><meta name="robots" content="${(noindex||editorial||sanatanPreview)?'noindex, follow':'index, follow'}"/><link rel="canonical" href="${url}"/><link rel="alternate" hreflang="en" href="https://spritual.co.in/${route}"/><link rel="alternate" hreflang="hi" href="https://spritual.co.in/hi/${route}"/><link rel="alternate" hreflang="x-default" href="https://spritual.co.in/${route}"/><meta property="og:type" content="website"/><meta property="og:title" content="${title}"/><meta property="og:description" content="${esc(description)}"/><meta property="og:url" content="${url}"/><meta property="og:site_name" content="Spritual"/><meta property="og:image" content="https://spritual.co.in/assets/social.png"/><meta property="og:image:width" content="1200"/><meta property="og:image:height" content="630"/><meta property="og:locale" content="${lang==='hi'?'hi_IN':'en_IN'}"/><meta name="twitter:card" content="summary_large_image"/><link rel="icon" href="/assets/brand.svg" type="image/svg+xml"/><link rel="preload" as="font" href="/assets/fraunces-latin.woff2" type="font/woff2" crossorigin/><script src="/theme-init.js"></script><link rel="stylesheet" href="/site.css"/><link rel="stylesheet" href="/library.css"/>${sanatan?'<link rel="stylesheet" href="/reading.css"/>':''}<script type="module" src="/site.js"></script></head><body data-page="${route||'home'}" data-route-world="${context}">${editorial?'<div class="editorial-banner">LOCAL EDITORIAL PREVIEW — NOT APPROVED FOR PUBLICATION</div>':''}${sanatanPreview?'<div class="editorial-banner">LOCAL SANATAN RELEASE PREVIEW — NOT THE LIVE SITE</div>':''}${quiet?'':header(c,lang,route)}${body}${quiet?'':footer(c,lang)}<script type="application/json" id="page-copy">${JSON.stringify(c).replaceAll('<','\\u003c')}</script></body></html>`;}
const baseRoutes=sanatan?[['',storyHome],['pause/',pause],['privacy/',storyPrivacy],['corrections/',correctionsPage]]:[['',home],['pause/',pause],['privacy/',privacy]];
for(const [lang,c] of Object.entries(copy)) for(const [route,render] of baseRoutes){let dir=`${out}/${lang==='hi'?'hi/':''}${route}`;await mkdir(dir,{recursive:true});const body=sanatan&&route!=='pause/'?render(lang):render(c,lang),description=route===''?(lang==='hi'?'परिवारों, युवा जिज्ञासुओं और बुज़ुर्गों के लिए दस निःशुल्क, स्रोत-सजग रामायण पुनर्कथन।':'Ten free, source-aware Ramayana retellings for families, young seekers and elders.'):route==='privacy/'?(lang==='hi'?'डिवाइस पर रहने वाली पठन-प्रगति, बुकमार्क और पसंद के बारे में स्पष्ट जानकारी।':'Clear information about device-only reading progress, bookmarks and preferences.'):route==='corrections/'?(lang==='hi'?'सार्वजनिक सुधार मार्ग और समीक्षा-पारदर्शिता।':'Public correction route and review transparency.'):null,title=route===''&&sanatan?(lang==='hi'?'पढ़ने, मनन करने और साथ बाँटने की कथाएँ — Spritual':'Stories to read, reflect on, and share — Spritual'):route==='corrections/'?(lang==='hi'?'सुधार की सूचना दें — Spritual':'Report a correction — Spritual'):null;await writeFile(`${dir}index.html`,page(c,lang,route,body,route==='privacy/',title,sanatan?description:null));}
const libraryRoutes=[];
function iconizeLibrary(body){return body.replaceAll('>↗</span>',`>${arrowOut}</span>`).replaceAll(' ↗',arrowOut).replaceAll(' →',arrow).replaceAll('← ',arrowBack).replaceAll(' ↓',arrowDown);}
async function writeLibrary(lang,route,body,title,description=null){const dir=`${out}/${lang==='hi'?'hi/':''}${route}`;await mkdir(dir,{recursive:true});await writeFile(`${dir}index.html`,page(copy[lang],lang,route,iconizeLibrary(body),route==='library/saved/',title+' — Spritual',description));libraryRoutes.push(`${lang==='hi'?'hi/':''}${route}`);}
for(const lang of ['en','hi']){
 await writeLibrary(lang,'library/',sanatan?storyLibrary(lang):libraryHome(lang),lang==='hi'?'पुस्तकालय':'Library',sanatan?(lang==='hi'?'आयु-सुझाव, मूल्य और पठन-समय के अनुसार दस निःशुल्क रामायण कथाएँ खोजें।':'Search ten free Ramayana stories by age guidance, value and reading time.'):null);
 await writeLibrary(lang,'library/saved/',sanatan?myReadingPage(lang):savedPage(lang),lang==='hi'?'सहेजे स्थान':'Saved places',sanatan?(lang==='hi'?'केवल इस डिवाइस पर सहेजी गई पठन-प्रगति और बुकमार्क देखें।':'Open reading progress and bookmarks saved only on this device.'):null);
 for(const c of collections){await writeLibrary(lang,`library/${c.id}/`,collectionPage(c,lang,staged),c.title[lang]);for(const u of c.units)await writeLibrary(lang,`library/${c.id}/${u.id}/`,richUnitPage(c,u,lang,staged),u.title[lang]);}
}
if(sanatan)for(const lang of ['en','hi']){
 const c=copy[lang];
 const writeStory=async(route,body,title,description,noindex=false)=>{const dir=`${out}/${lang==='hi'?'hi/':''}${route}`;await mkdir(dir,{recursive:true});await writeFile(`${dir}index.html`,page(c,lang,route,body,noindex,title+' — Spritual',description));};
 await writeStory('daily/',dailyPage(lang),lang==='hi'?'आज की कथा':'Today’s story',lang==='hi'?'दस पूर्ण कथाओं के पुस्तकालय से आज का शांत, बिना स्ट्रीक वाला निमंत्रण।':'A gentle, streak-free daily invitation from the same ten-story library.',true);
 await writeStory('my-reading/',myReadingPage(lang),lang==='hi'?'मेरा पठन':'My reading',lang==='hi'?'केवल इस डिवाइस पर सहेजी गई पठन-प्रगति और बुकमार्क देखें।':'Open reading progress and bookmarks saved only on this device.',true);
 for(const story of stories){const description=pick(story.description,lang);await writeStory(`story/${story.id}/`,storyDetail(story,lang),pick(story.title,lang),description);await writeStory(`read/${story.id}/`,storyReader(story,lang),pick(story.title,lang),description,true);}
 for(const character of Object.values(characters))await writeStory(`characters/${character.slug}/`,characterPage(character,lang),pick(character.name,lang),pick(character.bio,lang));
}
if(editorial){await mkdir(`${out}/sources`,{recursive:true});for(const source of staged.sources)await copyFile(resolve(import.meta.dirname,`../artifacts/library-source/pg${source.id}.txt`),`${out}/sources/pg${source.id}.txt`);for(const c of collections)for(const u of c.units){const record=staged.units[`${c.id}/${u.id}`];if(!record)continue;for(const ch of record.chapters){const route=`library/${c.id}/${u.id}/read/${ch.id}/`;const dir=`${out}/${route}`;await mkdir(dir,{recursive:true});await writeFile(`${dir}index.html`,page(copy.en,'en',`library/${c.id}/${u.id}/`,editorialReader(c,u,ch,record.chapters,record.introduction),true,ch.title+' — Editorial preview'));}}}
await writeFile(`${out}/404.html`,page(copy.en,'en','',`<main class="notfound wrap" id="main">${sun}<p class="eyebrow">404</p><h1>${copy.en.notfound}</h1><p>${copy.en.notfoundText}</p><a href="/" class="button">${copy.en.back}${arrow}</a></main>`,true));
await writeFile(`${out}/robots.txt`,'User-agent: *\nAllow: /\nSitemap: https://spritual.co.in/sitemap.xml\n');
await writeFile(`${out}/sitemap.xml`,`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['','hi/','pause/','hi/pause/',...(sanatan?['corrections/','hi/corrections/']:[]),...libraryRoutes.filter(r=>!r.endsWith('saved/')),...(sanatan?storySitemapRoutes():[])].map(p=>`<url><loc>https://spritual.co.in/${p}</loc></url>`).join('')}</urlset>`);
try { await copyFile(resolve(import.meta.dirname,'assets/social.png'),`${out}/assets/social.png`); } catch { console.warn('Social image not yet generated.'); }
console.log(`Built ${libraryRoutes.length+(sanatan?8+(storyGeneratedRoutes().length*2):6)} ${sanatanPreview?'local release preview':editorial?'local editorial preview':'public'} pages + 404${editorial?' and local-only imported reader pages':''}.`);
