import { mkdir, readFile, writeFile, copyFile, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { copy } from './content.mjs';
const out=resolve(import.meta.dirname,'dist');
await rm(out,{recursive:true,force:true}); await mkdir(out,{recursive:true}); await mkdir(`${out}/assets`);
// Deliberate allowlist: the local app's content, artwork, auth and fixture bundle are never deployed here.
for(const file of ['brand.svg','landscape.svg','fraunces-latin.woff2','OFL-Fraunces.txt']) await copyFile(resolve(import.meta.dirname,'assets',file),`${out}/assets/${file}`);
for(const file of ['site.css','site.js','session.mjs']) await copyFile(resolve(import.meta.dirname,file),`${out}/${file === 'session.mjs' ? 'session.js' : file}`);
const arrow='<svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const sun='<svg aria-hidden="true" viewBox="0 0 64 64" fill="none"><g stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><path d="M9 43h46M18 36a14 14 0 0 1 28 0M32 7v9M9 17l7 7M55 17l-7 7M10 52h44"/></g></svg>';
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function header(c,lang,route){const base=lang==='hi'?'/hi/':'/';return `<a class="skip" href="#main">${c.skip}</a><header class="header wrap"><a class="brand" href="${base}" aria-label="Spritual ${lang==='hi'?'मुखपृष्ठ':'home'}"><img src="/assets/brand.svg" width="40" height="40" alt=""/><span>Spritual<span class="brand-dot">.</span></span></a><nav aria-label="${lang==='hi'?'मुख्य नेविगेशन':'Main navigation'}"><a href="${base}#experience">${c.nav[0]}</a><a href="${base}#approach">${c.nav[1]}</a><a href="${base}#questions">${c.nav[2]}</a></nav><div class="header-actions"><a class="language" href="${c.other}${route}" lang="${lang==='hi'?'en':'hi'}" hreflang="${lang==='hi'?'en':'hi'}">${c.language}</a><a class="button small" href="${base}pause/">${c.cta}${arrow}</a></div></header>`;}
function footer(c,lang){let b=lang==='hi'?'/hi/':'/';return `<footer class="footer wrap"><div><a class="brand" href="${b}"><img src="/assets/brand.svg" width="36" height="36" alt=""/><span>Spritual.</span></a><p>${c.footerLine}</p></div><div class="footer-links"><a href="${b}privacy/">${c.privacy}</a><a href="${b}#app">${c.status}</a><span>© 2026 Spritual</span></div><p class="footer-note">${c.footerNote}</p></footer>`;}
function home(c,lang){let b=lang==='hi'?'/hi/':'/';return `<main id="main">
<section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="small-sun">✦</span>${c.eyebrow}</p><h1>${c.hero}</h1><p class="hero-intro">${c.intro}</p><p class="hero-lead">${c.lead}</p><div class="hero-actions"><a class="button" href="${b}pause/">${c.cta}${arrow}</a><a class="text-link" href="#experience">${c.discover}<span aria-hidden="true">↗</span></a></div><p class="fine">${c.free}</p></div><div class="hero-visual"><div class="arch-frame"><img class="landscape" src="/assets/landscape.svg" width="900" height="1120" fetchpriority="high" alt=""/><div class="art-caption"><span class="eyebrow">${c.artLabel}</span><p>${c.artTitle}</p></div><a class="art-play" href="${b}pause/" aria-label="${c.cta}"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="m9 5 11 7-11 7Z"/></svg></a></div><div class="orbit-seal" aria-hidden="true">${sun}<span>STILLNESS<br>WITHIN</span></div><div class="art-footer"><span>${lang==='hi'?'60 सेकंड':'60 SECONDS'}</span><span>${c.artFoot}</span><span aria-hidden="true">↗</span></div></div></section>
<div class="trust wrap">${c.trust.map(t=>`<span><span class="trust-star" aria-hidden="true">✦</span>${t}</span>`).join('')}</div>
<section class="section wrap" id="experience"><div class="section-heading"><div><p class="eyebrow">${c.experienceLabel}</p><h2>${c.experienceTitle}</h2></div><p class="section-intro">${c.experienceIntro}</p></div><div class="pillars">${c.pillars.map((p,i)=>`<article class="pillar reveal"><span class="number">0${i+1}</span><h3>${p[0]}</h3><p>${p[1]}</p><span class="eyebrow pillar-caption">${p[2]}</span></article>`).join('')}</div><p class="development-note">${c.develop}</p></section>
<section class="moments" id="moments"><div class="wrap moments-grid"><div><p class="eyebrow">${c.momentsLabel}</p><h2>${c.momentsTitle}</h2><p>${c.momentsIntro}</p><div class="moment-tabs" role="group" aria-label="${c.momentsLabel}">${c.moments.map((m,i)=>`<button type="button" data-moment="${i}" aria-pressed="${i===0}">${m[0]}<span aria-hidden="true">↗</span></button>`).join('')}</div></div><div class="reflection-card reveal"><div class="reflection-top"><span class="eyebrow">${c.sample}</span>${sun}</div><div id="moment-copy" aria-live="polite"><h3>${c.moments[0][1]}</h3><p>${c.moments[0][2]}</p></div><a id="moment-link" class="text-link" href="${b}pause/?moment=stillness">${c.momentAction}${arrow}</a><span class="fine">${c.momentNote}</span><div class="reflection-lines" aria-hidden="true"></div></div></div></section>
<section class="philosophy" id="approach"><div class="wrap"><p class="eyebrow">${c.philosophyLabel}</p><h2>${c.philosophy}</h2><p class="philosophy-intro">${c.philosophyText}</p><div class="principles">${c.principles.map((p,i)=>`<div class="reveal"><span aria-hidden="true">${['✧','◌','↗'][i]}</span><h3>${p[0]}</h3><p>${p[1]}</p></div>`).join('')}</div></div><div class="philosophy-orbits" aria-hidden="true"></div></section>
<section class="section wrap app-section" id="app"><div class="phone-stage reveal"><div class="phone"><div class="phone-top"><span>Spritual.</span>${sun}</div><p class="eyebrow">${c.phoneLabel}</p><h3>${c.phoneTitle}</h3><div class="phone-art"><img src="/assets/landscape.svg" alt="" loading="lazy" width="900" height="1120"/></div><p class="phone-text">${c.phoneText}</p><a class="button" href="${b}pause/">${c.cta}${arrow}</a><span class="phone-bottom">${c.phoneBottom}</span></div><span class="phone-orbit" aria-hidden="true"></span></div><div class="app-copy"><p class="eyebrow">${c.appLabel}</p><h2>${c.appTitle}</h2><p>${c.appText}</p><ul>${c.appPoints.map(x=>`<li>${x}</li>`).join('')}</ul><div class="availability"><span class="status-dot" aria-hidden="true"></span><strong>${c.appStatus}</strong><p>${c.appNote}</p></div></div></section>
<section class="faq wrap section" id="questions"><div><p class="eyebrow">${c.nav[2]}</p><h2>${c.faqTitle}</h2></div><div>${c.faqs.map((f,i)=>`<details><summary>${f[0]}<span aria-hidden="true">+</span></summary><p>${f[1]}</p></details>`).join('')}</div></section>
<section class="final-cta"><div class="wrap">${sun}<p class="eyebrow">${c.finalLabel}</p><h2>${c.finalTitle}</h2><p>${c.finalText}</p><a class="button" href="${b}pause/">${c.cta}${arrow}</a><span class="fine">${c.free}</span></div></section></main>`;}
function pause(c,lang){let b=lang==='hi'?'/hi/':'/';return `<main id="main" class="pause-main wrap"><a class="text-link back" href="${b}">← ${c.back}</a><div class="pause-layout"><aside class="pause-art"><img src="/assets/landscape.svg" width="900" height="1120" alt=""/><div><p class="eyebrow">${c.sample}</p><h2 id="pause-reflection">${c.moments[0][1]}</h2></div></aside><div class="pause-content"><section id="timer-view"><p class="eyebrow">${c.pauseTag}</p><h1>${c.pauseTitle}</h1><p>${c.pauseIntro}</p><div class="timer-dial" id="timer-dial"><svg viewBox="0 0 220 220" aria-hidden="true"><circle cx="110" cy="110" r="102"/><circle id="timer-progress" cx="110" cy="110" r="102" pathLength="60"/></svg><div><span id="time" role="timer" aria-label="${c.remaining}">1:00</span><span>${c.remaining}</span></div></div><p class="timer-status" id="timer-status" role="status">${c.ready}</p><div class="timer-controls"><button id="timer-toggle" class="button">${c.start}${arrow}</button><button id="timer-reset" class="text-button" hidden>${c.reset}</button></div><button id="finish" class="text-button finish-button">${c.finish} ↗</button><p class="fine">${c.silence}</p></section>
<section id="finish-view" hidden><p class="eyebrow">${c.finalLabel}</p><h1 tabindex="-1" id="finish-heading">${c.finishTitle}</h1><p>${c.finishText}</p><fieldset><legend>${c.stepLabel}</legend>${c.steps.map((s,i)=>`<label class="step-option"><input type="radio" name="intention" value="${i}"/><span>${s}</span></label>`).join('')}</fieldset><button class="button" id="save-step">${c.save}${arrow}</button><p class="fine">${c.savingNote}</p><p id="save-status" role="status"></p><a class="text-link" href="${b}">${c.finishNoSave}${arrow}</a></section>
<section id="saved-panel" class="saved-panel" hidden><p class="eyebrow">${c.savedHeading}</p><p id="saved-text"></p><button class="text-button" id="remove-step">${c.remove}</button><p id="remove-status" role="status"></p></section><div class="share-area"><button class="text-button" id="share-link">${c.share} ↗</button><p id="share-status" role="status"></p><label id="copy-fallback" hidden>${c.copyError}<input id="copy-url" readonly type="url"/></label></div><noscript><p class="notice">${c.noJS}</p></noscript></div></div></main>`;}
function privacy(c,lang){let b=lang==='hi'?'/hi/':'/';return `<main class="legal wrap" id="main"><a class="text-link" href="${b}">← ${c.back}</a><p class="eyebrow">${c.privacy}</p><h1>${c.privacyTitle}</h1><p class="lead">${c.privacyIntro}</p>${c.privacySections.map((p,i)=>`<section><h2>${p[0]}</h2><p>${p[1]}</p>${i===2?'<a href="https://vercel.com/legal/privacy-policy" rel="noreferrer">Vercel Privacy Notice ↗</a>':''}</section>`).join('')}<a class="button" href="${b}pause/">${c.savedHeading}${arrow}</a></main>`;}
function page(c,lang,route,body,noindex=false){let url=`https://spritual.co.in/${lang==='hi'?'hi/':''}${route}`;let title=route==='pause/'?`${c.pauseTitle} — Spritual`:route==='privacy/'?`${c.privacy} — Spritual`:c.title;return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>${title}</title><meta name="description" content="${esc(c.description)}"/><meta name="theme-color" content="#f6f3eb"/><meta name="robots" content="${noindex?'noindex, follow':'index, follow'}"/><link rel="canonical" href="${url}"/><link rel="alternate" hreflang="en" href="https://spritual.co.in/${route}"/><link rel="alternate" hreflang="hi" href="https://spritual.co.in/hi/${route}"/><link rel="alternate" hreflang="x-default" href="https://spritual.co.in/${route}"/><meta property="og:type" content="website"/><meta property="og:title" content="${title}"/><meta property="og:description" content="${esc(c.description)}"/><meta property="og:url" content="${url}"/><meta property="og:site_name" content="Spritual"/><meta property="og:image" content="https://spritual.co.in/assets/social.png"/><meta property="og:image:width" content="1200"/><meta property="og:image:height" content="630"/><meta property="og:locale" content="${lang==='hi'?'hi_IN':'en_IN'}"/><meta name="twitter:card" content="summary_large_image"/><link rel="icon" href="/assets/brand.svg" type="image/svg+xml"/><link rel="preload" as="font" href="/assets/fraunces-latin.woff2" type="font/woff2" crossorigin/><link rel="stylesheet" href="/site.css"/><script type="module" src="/site.js"></script></head><body data-page="${route||'home'}">${header(c,lang,route)}${body}${footer(c,lang)}<script type="application/json" id="page-copy">${JSON.stringify(c).replaceAll('<','\\u003c')}</script></body></html>`;}
for(const [lang,c] of Object.entries(copy)) for(const [route,render] of [['',home],['pause/',pause],['privacy/',privacy]]){let dir=`${out}/${lang==='hi'?'hi/':''}${route}`;await mkdir(dir,{recursive:true});await writeFile(`${dir}index.html`,page(c,lang,route,render(c,lang),route==='privacy/'));}
await writeFile(`${out}/404.html`,page(copy.en,'en','',`<main class="notfound wrap" id="main">${sun}<p class="eyebrow">404</p><h1>${copy.en.notfound}</h1><p>${copy.en.notfoundText}</p><a href="/" class="button">${copy.en.back}${arrow}</a></main>`,true));
await writeFile(`${out}/robots.txt`,'User-agent: *\nAllow: /\nSitemap: https://spritual.co.in/sitemap.xml\n');
await writeFile(`${out}/sitemap.xml`,`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['','hi/','pause/','hi/pause/'].map(p=>`<url><loc>https://spritual.co.in/${p}</loc></url>`).join('')}</urlset>`);
try { await copyFile(resolve(import.meta.dirname,'assets/social.png'),`${out}/assets/social.png`); } catch { console.warn('Social image not yet generated.'); }
console.log('Built six static pages + 404. No app fixtures, third-party runtime requests, credentials or dependencies included.');
