// Bibliographic navigation only. Religious prose is kept out of the public build.
const pair=(en,hi)=>({en,hi});
const mahaNames=[['adi','Adi Parva','आदि पर्व'],['sabha','Sabha Parva','सभा पर्व'],['vana','Vana Parva','वन पर्व'],['virata','Virata Parva','विराट पर्व'],['udyoga','Udyoga Parva','उद्योग पर्व'],['bhishma','Bhishma Parva','भीष्म पर्व'],['drona','Drona Parva','द्रोण पर्व'],['karna','Karna Parva','कर्ण पर्व'],['shalya','Shalya Parva','शल्य पर्व'],['sauptika','Sauptika Parva','सौप्तिक पर्व'],['stri','Stri Parva','स्त्री पर्व'],['shanti','Shanti Parva','शान्ति पर्व'],['anushasana','Anushasana Parva','अनुशासन पर्व'],['ashvamedhika','Ashvamedhika Parva','आश्वमेधिक पर्व'],['ashramavasika','Ashramavasika Parva','आश्रमवासिक पर्व'],['mausala','Mausala Parva','मौसल पर्व'],['mahaprasthanika','Mahaprasthanika Parva','महाप्रस्थानिक पर्व'],['svargarohana','Svargarohana Parva','स्वर्गारोहण पर्व']];
const ramaNames=[['bala','Bala Kanda','बाल काण्ड'],['ayodhya','Ayodhya Kanda','अयोध्या काण्ड'],['aranya','Aranya Kanda','अरण्य काण्ड'],['kishkindha','Kishkindha Kanda','किष्किन्धा काण्ड'],['sundara','Sundara Kanda','सुन्दर काण्ड'],['yuddha','Yuddha Kanda','युद्ध काण्ड'],['uttara','Uttara Kanda','उत्तर काण्ड']];
const shivaNames=[['vidyeshvara','Vidyeshvara Samhita','विद्येश्वर संहिता'],['rudra','Rudra Samhita','रुद्र संहिता'],['shatarudra','Shatarudra Samhita','शतरुद्र संहिता'],['kotirudra','Kotirudra Samhita','कोटिरुद्र संहिता'],['uma','Uma Samhita','उमा संहिता'],['kailasa','Kailasa Samhita','कैलास संहिता'],['vayaviya','Vayaviya Samhita','वायवीय संहिता']];
export const collections=[
 {id:'mahabharata',title:pair('Mahabharata','महाभारत'),subtitle:pair('A place for the larger questions.','जीवन के बड़े प्रश्नों के लिए एक जगह।'),kind:pair('18 parvas · source directory','18 पर्व · स्रोत निर्देशिका'),motif:'wheel',color:'moss',source:'https://www.gutenberg.org/ebooks/15474',edition:pair('Kisari Mohan Ganguli · English prose · 1883–1896','किसारी मोहन गांगुली · अंग्रेज़ी गद्य · 1883–1896'),note:pair('All 18 parvas are mapped here. The four-volume historical English edition is linked below. Spritual’s own reviewed reading edition is not published yet.','यहाँ सभी 18 पर्वों की सूची है। चार खण्डों का ऐतिहासिक अंग्रेज़ी संस्करण नीचे दिया गया है। Spritual का समीक्षित पाठ अभी प्रकाशित नहीं है।'),units:mahaNames.map(([id,en,hi],i)=>({id,title:pair(en,hi),source:`https://www.gutenberg.org/ebooks/${i<3?15474:i<7?15475:i<12?15476:15477}`,number:i+1}))},
 {id:'ramayana',title:pair('Ramayana','रामायण'),subtitle:pair('An epic to approach, one book at a time.','एक-एक काण्ड के साथ आगे बढ़ें।'),kind:pair('7 kandas · source directory','7 काण्ड · स्रोत निर्देशिका'),motif:'river',color:'clay',source:'https://www.gutenberg.org/ebooks/57265',edition:pair('Manmatha Nath Dutt · historical English prose edition','मन्मथ नाथ दत्त · ऐतिहासिक अंग्रेज़ी गद्य संस्करण'),note:pair('All seven kandas are mapped to the four-volume Manmatha Nath Dutt edition, including a separate Uttara Kanda volume. Spritual’s reviewed reading edition is not published yet. Valmiki’s Ramayana and Tulsidas’s Ramcharitmanas are distinct works.','यहाँ मन्मथ नाथ दत्त के चार-खण्ड संस्करण के सातों काण्डों की सूची है, जिसमें उत्तर काण्ड का अलग खण्ड भी है। Spritual का समीक्षित पाठ अभी प्रकाशित नहीं है। वाल्मीकि रामायण और तुलसीदास की रामचरितमानस अलग रचनाएँ हैं।'),units:ramaNames.map(([id,en,hi],i)=>({id,title:pair(en,hi),source:`https://www.gutenberg.org/ebooks/${i<2?57265:i<5?57826:i===5?60188:62496}`,number:i+1}))},
 {id:'shiva',title:pair('Shiva · stories & sources','शिव · कथाएँ और स्रोत'),subtitle:pair('Many tellings. Room for their differences.','अनेक कथाएँ। उनकी भिन्नताओं के लिए स्थान।'),kind:pair('7 samhitas · source directory','7 संहिताएँ · स्रोत निर्देशिका'),motif:'moon',color:'indigo',source:'https://www.wisdomlib.org/hinduism/book/shiva-purana-english',edition:pair('Shiva Purana · J. L. Shastri edition listed by Wisdom Library','शिव पुराण · Wisdom Library पर जे. एल. शास्त्री का संस्करण'),note:pair('Shiva stories occur across more than one text and tradition. This starting directory follows the seven-samhita Shiva Purana edition listed by Wisdom Library; it does not claim to contain every Shiva story. Permission to republish that modern translation has not been established.','शिव की कथाएँ कई ग्रन्थों और परम्पराओं में मिलती हैं। यह आरम्भिक सूची Wisdom Library के सात-संहिता शिव पुराण संस्करण पर आधारित है; यह शिव की हर कथा का दावा नहीं करती। आधुनिक अनुवाद को दोबारा प्रकाशित करने की अनुमति अभी सुनिश्चित नहीं है।'),units:shivaNames.map(([id,en,hi],i)=>({id,title:pair(en,hi),source:'https://www.wisdomlib.org/hinduism/book/shiva-purana-english',number:i+1}))}
];
export const localize=(value,lang)=>value[lang]||value.en;
export const findUnit=id=>collections.flatMap(c=>c.units.map(u=>({...u,collection:c,key:`${c.id}/${u.id}`}))).find(u=>u.key===id);
export const allKeys=collections.flatMap(c=>c.units.map(u=>`${c.id}/${u.id}`));
export const releasePolicy={version:1,paidAccessEnabled:false,provider:null,currency:null,price:null};
// Static output must never contain restricted or paid bodies. A future paid reader
// must authorize content server-side; a JavaScript lock is not an entitlement.
export function canPublishBody(record){return record?.rights?.status==='cleared'&&record.rights.evidence&&record.rights.territories==='worldwide'&&record?.review?.status==='approved'&&record.review.reviewer&&record.review.version===record.version&&record.access==='free';}
