export const copy = {
 en: {
  title:'Spritual — ancient wisdom, everyday life', description:'Meet Spritual: a calmer way to bring Indian spiritual wisdom into everyday life. Try a free, account-free quiet moment in English or Hindi.',
  nav:['The experience','Our approach','Questions'], cta:'Take a quiet moment', skip:'Skip to content', language:'हिन्दी', other:'/hi/',
  eyebrow:'ROOTED IN INDIA. OPEN TO YOUR EVERYDAY.', hero:'Ancient wisdom.<br>For the life<br><em>you’re living.</em>', intro:'A little understanding. A moment of stillness. One small thing to carry into your day.', lead:'We’re creating Spritual to bring scripture, stories and thoughtful practice closer to everyday life.', free:'A free 60-second pause · No account needed', discover:'Discover Spritual',
  artLabel:'A LITTLE SPACE TO BEGIN', artTitle:'Come back<br>to yourself.', artFoot:'A quiet moment, right here', trust:['Meaning before more content','English & हिन्दी','Your pace. No streaks.'],
  experienceLabel:'THE SPRITUAL WAY', experienceTitle:'Less scrolling.<br><em>More meaning.</em>', experienceIntro:'Spirituality can begin in an ordinary moment. A question on your commute. A story that stays with you. A little space before you respond.',
  pillars:[['Read with context.','Understand where a passage comes from and how its meaning is being explained. Source, translation and interpretation deserve their own space.','SOURCE → UNDERSTANDING'],['Let a story stay with you.','Explore the questions inside our traditions: courage, responsibility, attention and care. Not another feed to finish. Something to think with.','STORY → PERSPECTIVE'],['Carry one small thing.','Move from reading to a deliberate action. Keep a small intention, return when it helps, and begin again without a missed-day score.','REFLECTION → EVERYDAY LIFE']],
  develop:'The scripture and story library is in development. This website offers an original, non-scriptural pause you can try now.',
  momentsLabel:'BEGIN WHERE YOU ARE', momentsTitle:'What would feel<br><em>useful right now?</em>', momentsIntro:'There’s no right answer. Choose a starting point and make a little room for yourself.',
  moments:[['Slow down','You don’t have to solve everything in this moment.','Let the next minute belong to just one thing: being here.','stillness'],['Find focus','One thing deserves your attention.','Set the next task aside for a moment. Decide what needs you now.','focus'],['Be present','There is a whole moment here.','Notice something ordinary around you. Let it have your full attention.','presence']],
  sample:'AN ORIGINAL SPRITUAL REFLECTION', momentAction:'Begin this moment', momentNote:'Silent · 60 seconds · At your own pace',
  philosophyLabel:'A DIFFERENT KIND OF DAILY HABIT', philosophy:'A practice to return to.<br><em>Not a streak to protect.</em>', philosophyText:'Some days, a minute is enough. Some days, you’ll want to go deeper. Spritual is being built to respect both.', principles:[['Room for curiosity','You don’t need to know every verse or have all the answers.'],['Care with our sources','Sacred text, translation and original reflection should never be confused.'],['A life beyond the screen','The point is what you carry into your day, not how long you stay.']],
  appLabel:'THE APP WE’RE BUILDING', appTitle:'From a little reading<br>to <em>a lived moment.</em>', appText:'A calm companion for exploring Hindu and Sanatan wisdom, initially in English and Hindi. Read a little, follow the source, save what matters, and return to your place.', appPoints:['Scripture, stories and their source context','A gentle reading rhythm, without guilt','Optional personal steps and saved reading'], appStatus:'In development', appNote:'The full app and reviewed library are not publicly available yet. The quiet moment on this website is ready to use.', phoneLabel:'YOUR QUIET MOMENT', phoneTitle:'Begin with<br>one small thing.', phoneText:'Put one thing down.<br>Give this moment your attention.', phoneBottom:'A LITTLE, EVERY DAY',
  faqTitle:'A few things<br><em>you might wonder.</em>', faqs:[['What is Spritual?','Spritual is a spiritual learning app in development, rooted in Hindu and Sanatan traditions. The aim is to connect scripture, stories, source context and small everyday practices. This website introduces that vision and offers a free, original quiet-moment experience.'],['What can I use today?','You can take a silent pause, choose one of three original reflections, and optionally save a preset intention on this browser. The wider scripture library, narrated content, AI guidance and app-store releases are not available on this website.'],['Is the quiet moment a scripture teaching?','No. Its prompts are original everyday reflections written for Spritual. They are not quotations, translations, religious instruction or medical advice. Scripture content in the app has a separate source and human-review process before public release.'],['Do I need an account or subscription?','No. The website experience is free, with no account, payment or automatic renewal. Pricing for the future app has not been announced.'],['What happens to my saved intention?','Only the preset intention you explicitly choose to save is stored in this browser. It is not sent to a Spritual account and does not sync to another device. Anyone with access to this browser may see it. You can remove it on the quiet-moment page.'],['Can I use Spritual in Hindi?','Yes. The website and quiet-moment experience are available in English and Hindi. The app is being developed with those languages too.']],
  finalLabel:'YOU CAN BEGIN SMALL', finalTitle:'A little less noise.<br><em>A little more you.</em>', finalText:'Give the next minute to yourself.', footerLine:'Ancient wisdom. Everyday life.', footerNote:'Made with care, for a little meaning every day.', privacy:'Privacy & your data', status:'Website live · App in development', back:'Back to Spritual',
  pauseTitle:'A quiet moment', pauseIntro:'Settle wherever you are. Let your breathing be natural. Nothing to achieve, and nothing to get right.', pauseTag:'ONE MINUTE, JUST FOR YOU', start:'Begin my pause', resume:'Continue my pause', pause:'Pause timer', reset:'Start again', finish:'Finish my moment', remaining:'remaining', ready:'Ready when you are.', running:'Simply be here. Let your breathing be natural.', paused:'Paused. Return whenever you’re ready.', hidden:'Your timer paused while this page was away.', done:'Your minute is here. Stay a little longer, or finish when you’re ready.', silence:'A silent pause. No audio will play.', finishTitle:'Take a little of this<br><em>into your day.</em>', finishText:'Choose a small intention, if it feels useful. There is no score to keep.', stepLabel:'An optional next step', steps:['Give one task my full attention','Listen before I respond','Notice one ordinary good thing'], save:'Keep on this device', saved:'Your intention is kept on this device.', remove:'Remove saved intention', removed:'Your saved intention has been removed.', savingNote:'Saves only your chosen intention in this browser. It is unencrypted, visible to anyone using this browser, and never uploaded by this website.', storageError:'This browser could not save your intention. You can still take it with you.', removeError:'This browser could not remove the saved intention. Please try again.', corrupt:'A previous saved intention could not be read. Remove it before saving a new one.', finishNoSave:'Back to my day', share:'Copy a link to this pause', copied:'Link copied. It contains no saved intention.', copyError:'Copy this link manually:', savedHeading:'Your small intention', choose:'Choose an intention first.', noJS:'The optional timer needs JavaScript. You can still take a quiet minute: settle comfortably, notice what is around you, and choose one small thing to carry into your day.',
  privacyTitle:'A little clarity<br><em>about your data.</em>', privacyIntro:'This notice covers the Spritual website and its quiet-moment experience. Last updated 30 September 2026.', privacySections:[['What this website stores','Nothing from a pause is saved automatically. If you choose “Keep on this device”, the website stores one preset intention identifier in your browser’s local storage. It remains until you remove it or clear your browser data. It is unencrypted and may be visible to other people using this browser.'],['What this website does not collect','There is no account form, email waitlist, advertising tracker, analytics SDK, AI request, payment service or free-text journal on this website. Your chosen intention is not sent to our servers.'],['Hosting and ordinary requests','Vercel hosts this website. Loading any website sends ordinary connection information such as your IP address, requested URL and browser information to its hosting provider. Provider operational logs are separate from your saved intention. Vercel’s own privacy notice explains its processing.'],['Your controls','Open the quiet-moment page to see or remove a saved intention. Clearing this website’s storage in your browser also removes it. There is no cross-device recovery. Language links change the page URL; they do not create a profile.'],['About the app','The app is still in development. Any future accounts, AI features, subscriptions or data syncing will need their own clear disclosures before use. This website does not enroll you in those services.']], notfound:'A quieter path is this way.', notfoundText:'That page is not here. Return home or take a quiet moment.'
 },
 hi: {
 title:'Spritual — प्राचीन ज्ञान, रोज़मर्रा का जीवन', description:'Spritual से परिचय: भारतीय आध्यात्मिक ज्ञान को रोज़मर्रा के जीवन से जोड़ने की एक पहल। बिना खाते के एक मिनट का शांत ठहराव लें।',nav:['अनुभव','हमारी सोच','सवाल'],cta:'एक शांत पल लें',skip:'मुख्य विषय पर जाएँ',language:'English',other:'/',
 eyebrow:'भारत की जड़ों से। आपके हर दिन के लिए।',hero:'प्राचीन ज्ञान।<br>आपके जीवन के<br><em>थोड़ा और करीब।</em>',intro:'थोड़ी समझ। थोड़ा ठहराव। दिन में साथ ले जाने के लिए एक छोटी-सी बात।',lead:'Spritual में हम शास्त्रों, कथाओं और विचारपूर्ण अभ्यास को रोज़मर्रा के जीवन से जोड़ रहे हैं।',free:'एक मिनट का निःशुल्क ठहराव · खाते की ज़रूरत नहीं',discover:'Spritual को जानें',artLabel:'शुरुआत के लिए थोड़ी जगह',artTitle:'खुद के पास<br>फिर लौटें।',artFoot:'एक शांत पल, यहीं',trust:['अधिक सामग्री से पहले अर्थ','English और हिन्दी','आपकी गति। कोई स्ट्रीक नहीं।'],
 experienceLabel:'SPRITUAL का तरीका',experienceTitle:'थोड़ा कम स्क्रॉल।<br><em>थोड़ा अधिक अर्थ।</em>',experienceIntro:'आध्यात्मिकता एक साधारण पल से शुरू हो सकती है। रास्ते में उठा कोई सवाल। मन में रह गई कोई कथा। जवाब देने से पहले थोड़ा ठहराव।',pillars:[['संदर्भ के साथ पढ़ें।','जानें कि कोई अंश कहाँ से आया है और उसका अर्थ कैसे समझाया जा रहा है। मूल पाठ, अनुवाद और व्याख्या की अलग पहचान ज़रूरी है।','स्रोत → समझ'],['कथा को साथ रहने दें।','हमारी परंपराओं में साहस, ज़िम्मेदारी, ध्यान और करुणा के सवाल खोजें। सोचने के लिए कुछ, बस ख़त्म करने के लिए कोई फ़ीड नहीं।','कथा → दृष्टिकोण'],['एक छोटी बात साथ लें।','पढ़ने से आगे एक सोच-समझकर चुना कदम। छोटा संकल्प रखें, जब उपयोगी लगे लौटें, और बिना छूटे दिनों की गिनती के फिर शुरू करें।','मनन → रोज़मर्रा का जीवन']],develop:'शास्त्रों और कथाओं का संग्रह अभी बन रहा है। इस वेबसाइट पर आप हमारा मौलिक, गैर-शास्त्रीय शांत ठहराव आज़मा सकते हैं।',
 momentsLabel:'जहाँ हैं, वहीं से शुरू करें',momentsTitle:'अभी क्या<br><em>उपयोगी लगेगा?</em>',momentsIntro:'कोई सही या गलत जवाब नहीं। एक शुरुआत चुनें और अपने लिए थोड़ी जगह बनाएँ।',moments:[['थोड़ा ठहरें','इस पल हर बात सुलझाना ज़रूरी नहीं।','अगला मिनट बस यहीं होने के नाम करें।','stillness'],['ध्यान जुटाएँ','एक काम आपका ध्यान माँगता है।','अगले काम को थोड़ी देर रहने दें। तय करें कि अभी किस बात को आपका समय चाहिए।','focus'],['इस पल में रहें','इस पल में भी बहुत कुछ है।','आसपास की किसी साधारण चीज़ पर ध्यान दें। एक पल उसे पूरा समय दें।','presence']],sample:'SPRITUAL का एक मौलिक विचार',momentAction:'यह पल शुरू करें',momentNote:'शांत · 60 सेकंड · अपनी गति से',
 philosophyLabel:'हर दिन की एक अलग आदत',philosophy:'एक अभ्यास, जहाँ लौट सकें।<br><em>स्ट्रीक बचाने की चिंता नहीं।</em>',philosophyText:'कुछ दिन एक मिनट काफ़ी है। कुछ दिन आप और गहराई में जाना चाहेंगे। Spritual में दोनों के लिए जगह है।',principles:[['जिज्ञासा के लिए जगह','हर श्लोक जानना या हर जवाब होना ज़रूरी नहीं।'],['स्रोतों के प्रति सावधानी','मूल पाठ, अनुवाद और मौलिक विचार की पहचान साफ़ होनी चाहिए।'],['स्क्रीन से आगे का जीवन','मायने उस बात के हैं जो जीवन में साथ जाए, यहाँ बिताए समय के नहीं।']],
 appLabel:'हम जो ऐप बना रहे हैं',appTitle:'थोड़ा पढ़ें।<br><em>जीवन में साथ लें।</em>',appText:'हिन्दू और सनातन ज्ञान को जानने का एक शांत साथी, शुरुआत में अंग्रेज़ी और हिन्दी में। थोड़ा पढ़ें, स्रोत देखें, उपयोगी बात सहेजें और वहीं से फिर शुरू करें।',appPoints:['शास्त्र, कथाएँ और उनके स्रोत','बिना अपराधबोध के पढ़ने की लय','वैकल्पिक छोटे कदम और सहेजे पाठ'],appStatus:'अभी बन रहा है',appNote:'पूरा ऐप और समीक्षित संग्रह अभी सार्वजनिक रूप से उपलब्ध नहीं हैं। इस वेबसाइट का शांत ठहराव आप अभी इस्तेमाल कर सकते हैं।',phoneLabel:'आपका शांत पल',phoneTitle:'एक छोटी बात से<br>शुरू करें।',phoneText:'एक काम थोड़ी देर रहने दें।<br>इस पल को अपना ध्यान दें।',phoneBottom:'थोड़ा, हर दिन',
 faqTitle:'शायद आपके मन में<br><em>ये सवाल हों।</em>',faqs:[['Spritual क्या है?','Spritual हिन्दू और सनातन परंपराओं पर आधारित एक आध्यात्मिक अध्ययन ऐप है, जो अभी बन रहा है। इसका उद्देश्य शास्त्रों, कथाओं, स्रोत-संदर्भ और छोटे दैनिक अभ्यासों को जोड़ना है। यह वेबसाइट उस सोच का परिचय देती है और एक निःशुल्क मौलिक शांत पल प्रस्तुत करती है।'],['मैं आज क्या इस्तेमाल कर सकता हूँ?','आप शांत ठहराव ले सकते हैं, तीन मौलिक विचारों में से एक चुन सकते हैं और एक तय संकल्प इसी ब्राउज़र में सहेज सकते हैं। विस्तृत शास्त्र-संग्रह, कथावाचन, AI मार्गदर्शन और ऐप स्टोर संस्करण अभी इस वेबसाइट पर उपलब्ध नहीं हैं।'],['क्या यह ठहराव किसी शास्त्र की शिक्षा है?','नहीं। ये Spritual के लिए लिखे गए मौलिक दैनिक विचार हैं। ये उद्धरण, अनुवाद, धार्मिक निर्देश या चिकित्सा सलाह नहीं हैं। ऐप की शास्त्रीय सामग्री के सार्वजनिक होने से पहले स्रोत और मानव समीक्षा की अलग प्रक्रिया है।'],['क्या खाता या सदस्यता चाहिए?','नहीं। वेबसाइट का अनुभव निःशुल्क है। कोई खाता, भुगतान या स्वतः नवीनीकरण नहीं है। भविष्य के ऐप की कीमत अभी घोषित नहीं की गई है।'],['मेरा सहेजा संकल्प कहाँ रहता है?','सिर्फ़ वही तय संकल्प, जिसे आप सहेजते हैं, इस ब्राउज़र में रहता है। वह Spritual खाते में नहीं भेजा जाता और दूसरे उपकरण पर नहीं आता। इस ब्राउज़र का उपयोग करने वाला व्यक्ति उसे देख सकता है। आप शांत-पल पृष्ठ पर उसे हटा सकते हैं।'],['क्या Spritual हिन्दी में है?','हाँ। वेबसाइट और शांत-पल अनुभव अंग्रेज़ी और हिन्दी में हैं। ऐप भी इन दोनों भाषाओं को ध्यान में रखकर बनाया जा रहा है।']],
 finalLabel:'छोटी शुरुआत भी शुरुआत है',finalTitle:'थोड़ा कम शोर।<br><em>खुद के थोड़ा करीब।</em>',finalText:'अगला मिनट खुद को दें।',footerLine:'प्राचीन ज्ञान। रोज़मर्रा का जीवन।',footerNote:'थोड़े अर्थ के लिए, हर दिन।',privacy:'निजता और आपका डेटा',status:'वेबसाइट उपलब्ध · ऐप बन रहा है',back:'Spritual पर लौटें',
 pauseTitle:'एक शांत पल',pauseIntro:'जहाँ हैं, आराम से ठहरें। साँस को स्वाभाविक रहने दें। कुछ हासिल करने या सही करने का दबाव नहीं।',pauseTag:'एक मिनट, सिर्फ़ आपके लिए',start:'अपना ठहराव शुरू करें',resume:'ठहराव जारी रखें',pause:'टाइमर रोकें',reset:'फिर शुरू करें',finish:'अपना पल पूरा करें',remaining:'बाकी',ready:'जब आप तैयार हों।',running:'बस यहीं रहें। साँस को स्वाभाविक रहने दें।',paused:'रुका हुआ है। जब चाहें लौटें।',hidden:'पृष्ठ से दूर जाने पर टाइमर रुक गया।',done:'आपका मिनट पूरा हुआ। चाहें तो और ठहरें, या तैयार होने पर पूरा करें।',silence:'यह शांत ठहराव है। कोई ऑडियो नहीं बजेगा।',finishTitle:'इस पल की थोड़ी-सी बात<br><em>दिन में साथ लें।</em>',finishText:'उपयोगी लगे तो एक छोटा संकल्प चुनें। कोई अंक या गिनती नहीं है।',stepLabel:'एक वैकल्पिक अगला कदम',steps:['एक काम को पूरा ध्यान दूँगा/दूँगी','जवाब देने से पहले सुनूँगा/सुनूँगी','एक साधारण अच्छी बात पर ध्यान दूँगा/दूँगी'],save:'इसी उपकरण पर रखें',saved:'आपका संकल्प इस उपकरण पर रखा गया है।',remove:'सहेजा संकल्प हटाएँ',removed:'आपका सहेजा संकल्प हटा दिया गया है।',savingNote:'केवल चुना संकल्प इसी ब्राउज़र में सहेजता है। यह एन्क्रिप्टेड नहीं है, ब्राउज़र का उपयोग करने वाले को दिख सकता है और वेबसाइट इसे अपलोड नहीं करती।',storageError:'यह ब्राउज़र संकल्प सहेज नहीं पाया। आप इसे फिर भी अपने साथ ले जा सकते हैं।',removeError:'यह ब्राउज़र संकल्प हटा नहीं पाया। फिर कोशिश करें।',corrupt:'पिछला संकल्प पढ़ा नहीं जा सका। नया सहेजने से पहले उसे हटाएँ।',finishNoSave:'अपने दिन पर लौटें',share:'इस ठहराव का लिंक कॉपी करें',copied:'लिंक कॉपी हुआ। इसमें आपका संकल्प नहीं है।',copyError:'इस लिंक को स्वयं कॉपी करें:',savedHeading:'आपका छोटा संकल्प',choose:'पहले एक संकल्प चुनें।',noJS:'वैकल्पिक टाइमर के लिए JavaScript चाहिए। आप फिर भी एक शांत मिनट ले सकते हैं: आराम से बैठें, आसपास ध्यान दें और दिन में साथ ले जाने के लिए एक छोटी बात चुनें।',
 privacyTitle:'आपके डेटा के बारे में<br><em>थोड़ी स्पष्टता।</em>',privacyIntro:'यह सूचना Spritual वेबसाइट और शांत-पल अनुभव के लिए है। अंतिम बदलाव: 30 सितम्बर 2026।',privacySections:[['यह वेबसाइट क्या सहेजती है','ठहराव से कुछ भी अपने आप नहीं सहेजा जाता। “इसी उपकरण पर रखें” चुनने पर केवल तय संकल्प का पहचान-चिह्न ब्राउज़र के लोकल स्टोरेज में रहता है। आपके हटाने या ब्राउज़र डेटा साफ़ करने तक यह बना रहता है। यह एन्क्रिप्टेड नहीं है और इसी ब्राउज़र का उपयोग करने वाले को दिख सकता है।'],['यह वेबसाइट क्या इकट्ठा नहीं करती','इस वेबसाइट पर खाता-फ़ॉर्म, ईमेल सूची, विज्ञापन ट्रैकर, एनालिटिक्स SDK, AI अनुरोध, भुगतान या निजी डायरी नहीं है। आपका संकल्प हमारे सर्वर को नहीं भेजा जाता।'],['होस्टिंग और सामान्य अनुरोध','यह वेबसाइट Vercel पर होस्ट की जाती है। वेबसाइट खोलने पर IP पता, पृष्ठ का URL और ब्राउज़र जानकारी जैसी सामान्य कनेक्शन जानकारी होस्टिंग प्रदाता तक जाती है। प्रदाता के परिचालन लॉग आपके संकल्प से अलग हैं। Vercel की निजता सूचना में इसका विवरण है।'],['आपका नियंत्रण','शांत-पल पृष्ठ पर सहेजा संकल्प देखें या हटाएँ। ब्राउज़र में इस वेबसाइट का स्टोरेज साफ़ करने पर भी यह हटता है। दूसरे उपकरण पर वापस पाने की सुविधा नहीं है। भाषा बदलने से पृष्ठ का URL बदलता है, कोई प्रोफ़ाइल नहीं बनती।'],['ऐप के बारे में','ऐप अभी बन रहा है। भविष्य में खाते, AI, सदस्यता या डेटा सिंक जैसे विकल्पों के इस्तेमाल से पहले उनकी अलग स्पष्ट जानकारी होगी। यह वेबसाइट आपको उन सेवाओं में शामिल नहीं करती।']],notfound:'एक शांत रास्ता यहाँ है।',notfoundText:'यह पृष्ठ यहाँ नहीं है। मुखपृष्ठ पर लौटें या एक शांत पल लें।'
 }
};

// Current website capabilities; keep public copy and privacy aligned with shipped behavior.
copy.en.develop='Explore source guides for the Mahabharata, Ramayana and Shiva traditions. Spritual’s reviewed scripture editions and narrated stories are still in preparation.';
copy.hi.develop='महाभारत, रामायण और शिव परम्पराओं की स्रोत-मार्गदर्शिकाएँ देखें। Spritual के समीक्षित पाठ और कथावाचन की तैयारी अभी जारी है।';
copy.en.faqs[1][1]='You can browse 32 source guides, search the library, open external editions, save a reading place on this device, and take a quiet moment. Full Spritual scripture editions, narration, AI guidance and app-store releases are not available yet.';
copy.hi.faqs[1][1]='आप 32 स्रोत-मार्गदर्शिकाएँ देख सकते हैं, पुस्तकालय में खोज सकते हैं, बाहरी संस्करण खोल सकते हैं, इसी डिवाइस पर पढ़ने का स्थान सहेज सकते हैं और एक शांत पल ले सकते हैं। Spritual के पूर्ण पाठ, कथावाचन, AI मार्गदर्शन और ऐप-स्टोर रिलीज़ अभी उपलब्ध नहीं हैं।';
copy.en.privacySections[0][1]+=' If you explicitly choose “Save this place” in the library, we also store the selected section IDs in a separate local list. We do not automatically track your reading or save search queries. Text size and focus-view choices last only for the current page.';
copy.hi.privacySections[0][1]+=' पुस्तकालय में “यह स्थान सहेजें” चुनने पर चुने खण्डों की पहचान एक अलग स्थानीय सूची में रहती है। आपकी पढ़ाई या खोज अपने आप सहेजी नहीं जाती। अक्षर आकार और एकाग्र दृश्य के विकल्प केवल खुले पृष्ठ तक रहते हैं।';
copy.en.privacySections[1][1]+=' Your saved reading places are not uploaded either.';
copy.hi.privacySections[1][1]+=' आपके सहेजे पढ़ने के स्थान भी अपलोड नहीं होते।';
copy.en.privacySections[3][1]+=' In the library, open Saved places to remove any saved section. External source links open another website with its own privacy practices; we do not embed that website or load it before you choose the link.';
copy.hi.privacySections[3][1]+=' पुस्तकालय में सहेजे स्थान खोलकर कोई भी खण्ड हटा सकते हैं। बाहरी स्रोत-लिंक दूसरे वेबसाइट पर खुलते हैं, जिनकी अपनी निजता नीति होती है। लिंक चुनने से पहले हम वह वेबसाइट लोड नहीं करते।';
