// Draft original editorial orientation. This is not scripture text or translation.
// Every entry is intentionally marked unreviewed and source-rights-unknown.
const pair=(en,hi)=>({en,hi});
const src=(reference,url,scope='specific locator for further reading')=>({reference,url,scope});
const guide=(overview,figures,themes,reflection,sources,variantNote)=>({
  kind:'EDITORIAL_EXPLANATION',reviewState:'unreviewed',sourceRights:'unknown',
  overview:pair(...overview),figures:pair(...figures),themes:pair(...themes),
  reflection:pair(...reflection),sources,variantNote:variantNote?pair(...variantNote):null
});
const pg=(book,name,volume,url,selected)=>{const pick=Array.isArray(selected?.[0])?selected[0]:selected;return [
  src(`Mahabharata, Book ${book}, ${name}; Ganguli English prose edition, Project Gutenberg volume ${volume}`,`https://www.gutenberg.org/ebooks/${volume===1?15474:volume===2?15475:volume===3?15476:15477}`,'whole-book bibliographic locator'),
  ...(pick?[src(pick[0],pick[1],'verified opening or selected reading, not a citation for every event in the overview')]:[])
]};
export const guideContent={
  'mahabharata/adi':guide(
    ['The epic begins with people listening to a story already told elsewhere. Family histories, births, vows and rivalries establish the world of the Pandavas and Kauravas. Notice how inherited promises shape choices long before the war. Reading the opening as a web of relationships helps explain why later decisions resist simple judgments.','महाकाव्य की शुरुआत ऐसे श्रोताओं से होती है जो पहले कहीं सुनाई गई कथा सुन रहे हैं। वंश-कथाएँ, जन्म, प्रतिज्ञाएँ और प्रतिस्पर्धाएँ पाण्डवों तथा कौरवों की दुनिया बनाते हैं। युद्ध से बहुत पहले किए गए वचन आगे के चुनावों को प्रभावित करते हैं। संबंधों के इस जाल को समझने से बाद के निर्णयों की जटिलता खुलती है।'],
    [['Sauti','Vyasa','Bhishma','Kunti','Pandavas and Kauravas'],['सौति','व्यास','भीष्म','कुन्ती','पाण्डव और कौरव']],
    [['Story within story','Inheritance','Consequences of vows'],['कथा के भीतर कथा','विरासत','प्रतिज्ञाओं के परिणाम']],
    ['Which inherited expectation deserves a fresh look before you act on it?','किस विरासत में मिली अपेक्षा पर अमल करने से पहले नए सिरे से विचार करना चाहिए?'],
    pg(1,'Adi Parva',1,'',[['Adi Parva, section I (Ganguli numbering)','https://sacred-texts.com/hin/m01/m01002.htm']])
  ),
  'mahabharata/sabha':guide(
    ['A magnificent assembly hall and royal ambition lead into a disastrous game of dice. Draupadi challenges what the assembly is willing to accept, while powerful elders struggle or fail to respond. The book asks readers to examine both wrongdoing and the silence that allows it. Prestige offers little protection when judgment and accountability collapse.','भव्य सभा और राजसत्ता की महत्वाकांक्षा के बीच कथा विनाशकारी द्यूत-क्रीड़ा तक पहुँचती है। द्रौपदी सभा के सामने प्रश्न रखती हैं, जबकि प्रभावशाली बुज़ुर्ग उत्तर देने में उलझते या चूकते हैं। यह पर्व अन्याय के साथ उसे संभव बनाने वाले मौन को भी देखने को कहता है। विवेक और जवाबदेही टूटें तो प्रतिष्ठा पर्याप्त नहीं होती।'],
    [['Yudhishthira','Draupadi','Duryodhana','Shakuni','Vidura'],['युधिष्ठिर','द्रौपदी','दुर्योधन','शकुनि','विदुर']],
    [['Public responsibility','Gambling and power','Speaking against injustice'],['सार्वजनिक जिम्मेदारी','द्यूत और सत्ता','अन्याय के विरुद्ध प्रश्न']],
    ['When a group accepts something harmful, what would help you raise a clear objection?','समूह किसी हानिकारक बात को स्वीकार करे तो स्पष्ट आपत्ति उठाने में क्या मदद करेगा?'],
    pg(2,'Sabha Parva',1,'',[['Sabha Parva, section I (Ganguli numbering)','https://www.ibiblio.org/sripedia/ebooks/mb/m02/m02001.htm']])
  ),
  'mahabharata/vana':guide(
    ['Exile changes the Pandavas’ surroundings without ending their disagreements or responsibilities. Encounters with sages, journeys and stories interrupt the central struggle and offer other ways to think about loss. Draupadi and the brothers do not always agree about patience or action. Read their exchanges as a continuing argument about how to live through uncertainty.','वनवास पाण्डवों का परिवेश बदलता है, पर मतभेद और जिम्मेदारियाँ समाप्त नहीं करता। ऋषियों से भेंट, यात्राएँ और बीच में आने वाली कथाएँ हानि को समझने के अलग रास्ते खोलती हैं। धैर्य और कर्म पर द्रौपदी तथा भाइयों की राय हमेशा एक नहीं होती। उनके संवाद अनिश्चितता में जीने पर चलती बहस हैं।'],
    [['Draupadi','Yudhishthira','Bhima','Arjuna','Forest sages'],['द्रौपदी','युधिष्ठिर','भीम','अर्जुन','वन के ऋषि']],
    [['Exile','Patience and protest','Learning through stories'],['वनवास','धैर्य और प्रतिरोध','कथाओं से सीखना']],
    ['What could sustain you during a difficult period without asking you to ignore what is wrong?','अन्याय की अनदेखी किए बिना कठिन समय में कौन-सी बात आपको सहारा दे सकती है?'],
    pg(3,'Vana Parva',1,'',[['Vana Parva, section I (Ganguli numbering)','https://sacred-texts.com/hin/m03/m03001.htm']])
  ),
  'mahabharata/virata':guide(
    ['The Pandavas and Draupadi spend their concealed year in Virata’s kingdom, taking unfamiliar public roles while protecting their identities. Service, vulnerability and hidden ability replace royal display. The danger faced by Draupadi and the defence of Virata’s cattle make concealment increasingly difficult. This book invites attention to the skills and dignity that status can hide.','पाण्डव और द्रौपदी विराट के राज्य में अपनी पहचान छिपाकर अज्ञातवास बिताते हैं। राजसी प्रदर्शन की जगह सेवा, असुरक्षा और छिपी हुई क्षमता सामने आती है। द्रौपदी पर संकट तथा विराट के पशुधन की रक्षा से पहचान बचाना कठिन होता जाता है। यह पर्व उन योग्यताओं और गरिमा पर ध्यान दिलाता है जिन्हें पद अक्सर ढक देता है।'],
    [['Virata','Draupadi','Bhima','Arjuna as Brihannala','Prince Uttara, Virata’s son'],['विराट','द्रौपदी','भीम','बृहन्नला रूप में अर्जुन','राजकुमार उत्तर, विराट के पुत्र']],
    [['Identity','Hidden skill','Protection in vulnerability'],['पहचान','छिपी क्षमता','असुरक्षा में संरक्षण']],
    ['Whose abilities might you be overlooking because of the role they currently occupy?','किसी के वर्तमान पद के कारण आप उसकी कौन-सी योग्यता अनदेखी कर रहे हैं?'],
    pg(4,'Virata Parva',2,'',[['Virata Parva, section I (Ganguli numbering)','https://sacred-texts.com/hin/m04/m04001.htm']])
  ),
  'mahabharata/udyoga':guide(
    ['Before the armies meet, envoys, elders and relatives argue over peace, land and obligation. Krishna’s mission belongs to this wider effort to prevent war, even as alliances form and preparations accelerate. Listen for the difference between a genuine opening for agreement and a demand that merely postpones conflict. The coming battle is preceded by many choices.','सेनाओं के मिलने से पहले दूत, बुज़ुर्ग और संबंधी शांति, भूमि तथा कर्तव्य पर विचार करते हैं। कृष्ण का शांति-प्रयास इसी व्यापक क्रम का हिस्सा है; साथ ही गठबंधन और युद्ध की तैयारियाँ बढ़ती हैं। सच्चे समझौते की संभावना और संघर्ष को केवल टालने वाली माँग का अंतर देखें। युद्ध से पहले अनेक चुनाव किए जाते हैं।'],
    [['Krishna','Vidura','Sanjaya','Kunti','Duryodhana'],['कृष्ण','विदुर','संजय','कुन्ती','दुर्योधन']],
    [['Diplomacy','Competing loyalties','Preventable conflict'],['कूटनीति','परस्पर टकराती निष्ठाएँ','संघर्ष रोकने के अवसर']],
    ['What would a sincere attempt at agreement require from you, beyond repeating your position?','अपनी बात दोहराने से आगे, समझौते के सच्चे प्रयास में आपको क्या करना होगा?'],
    pg(5,'Udyoga Parva',2,'',[['Udyoga Parva, section I (Ganguli numbering)','https://sacred-texts.com/hin/m05/m05001.htm']])
  ),
  'mahabharata/bhishma':guide(
    ['The war opens under Bhishma’s command. Within this setting, Arjuna’s distress becomes the starting point of the Bhagavad Gita’s dialogue with Krishna. The surrounding battle narrative keeps the teaching connected to a difficult human situation. Read the dialogue with its questions intact, rather than treating isolated lines as ready-made answers to every problem.','भीष्म के सेनापतित्व में युद्ध शुरू होता है। इसी परिस्थिति में अर्जुन की व्याकुलता कृष्ण के साथ भगवद्गीता के संवाद का आरम्भ बनती है। आसपास की युद्ध-कथा उपदेश को कठिन मानवीय स्थिति से जोड़े रखती है। संवाद के प्रश्नों को साथ लेकर पढ़ें; अलग किए गए वाक्यों को हर समस्या का तैयार उत्तर न मानें।'],
    [['Bhishma','Arjuna','Krishna','Sanjaya','Dhritarashtra'],['भीष्म','अर्जुन','कृष्ण','संजय','धृतराष्ट्र']],
    [['Moral conflict','Teaching in context','War and kinship'],['नैतिक द्वंद्व','संदर्भ में उपदेश','युद्ध और संबंध']],
    ['Before seeking advice, can you describe the real conflict rather than only the outcome you want?','सलाह माँगने से पहले, क्या आप मनचाहे परिणाम के बजाय वास्तविक द्वंद्व बता सकते हैं?'],
    pg(6,'Bhishma Parva',2,'',[['Bhishma Parva, section XXV (Bhagavad Gita chapter 1), Ganguli numbering','https://www.ibiblio.org/sripedia/ebooks/mb/m06/m06025.htm']])
  ),
  'mahabharata/drona':guide(
    ['With Drona leading the Kaurava army, the fighting becomes increasingly destructive. Abhimanyu’s struggle, vows of revenge and the fate of the commander bring the means of winning into sharp focus. Military skill does not settle the question of right conduct. Follow how each loss changes the choices of people who remain on the battlefield.','द्रोण के कौरव सेना का नेतृत्व सँभालने पर युद्ध और विनाशकारी होता है। अभिमन्यु का संघर्ष, प्रतिशोध की प्रतिज्ञाएँ और सेनापति का अंत जीत के साधनों पर प्रश्न उठाते हैं। युद्ध-कौशल से उचित आचरण का प्रश्न हल नहीं होता। देखें कि हर हानि बचे हुए लोगों के अगले चुनाव को कैसे बदलती है।'],
    [['Drona','Abhimanyu','Arjuna','Yudhishthira','Ashvatthaman'],['द्रोण','अभिमन्यु','अर्जुन','युधिष्ठिर','अश्वत्थामा']],
    [['Escalation','Revenge','Ethical limits'],['बढ़ती हिंसा','प्रतिशोध','नैतिक सीमाएँ']],
    ['What limit would you want to preserve even when pressure to win becomes intense?','जीतने का दबाव बहुत बढ़ जाए तब भी आप कौन-सी सीमा बचाना चाहेंगे?'],
    pg(7,'Drona Parva',2,'',[['Drona Parva, section XXXV (Abhimanyu-badha), Ganguli numbering','https://www.ibiblio.org/sripedia/ebooks/mb/m07/m07035.htm']])
  ),
  'mahabharata/karna':guide(
    ['Karna takes command after Drona’s death, and his long rivalry with Arjuna moves toward its final encounter. Loyalty to Duryodhana, personal honour and accumulated conflict surround the battle. This is a place to hold admiration and criticism together: courage does not erase harmful choices, and a tragic end does not make a life simple.','द्रोण की मृत्यु के बाद कर्ण सेनापति बनते हैं और अर्जुन से उनकी पुरानी प्रतिस्पर्धा अंतिम सामना बनती है। दुर्योधन के प्रति निष्ठा, निजी सम्मान और पुराने संघर्ष युद्ध के साथ चलते हैं। यहाँ प्रशंसा और आलोचना साथ रखी जा सकती हैं: साहस हानिकारक निर्णय नहीं मिटाता, और दुखद अंत किसी जीवन को सरल नहीं बना देता।'],
    [['Karna','Arjuna','Shalya','Krishna','Duryodhana'],['कर्ण','अर्जुन','शल्य','कृष्ण','दुर्योधन']],
    [['Loyalty','Tragic rivalry','Honour and responsibility'],['निष्ठा','दुखद प्रतिस्पर्धा','सम्मान और जिम्मेदारी']],
    ['When does loyalty help someone, and when does it keep you from questioning their actions?','निष्ठा कब किसी का साथ देती है और कब उसके कर्मों पर प्रश्न करने से रोकती है?'],
    pg(8,'Karna Parva',3,'',[['Karna Parva, section 1 (Ganguli numbering)','https://sacred-texts.com/hin/m08/m08001.htm']])
  ),
  'mahabharata/shalya':guide(
    ['Shalya leads the remaining Kaurava forces as the war approaches its end. The narrative moves through the army’s collapse toward the mace duel between Bhima and Duryodhana. Disputes over how that contest is fought prevent victory from feeling uncomplicated. The book asks what remains of agreed rules when exhaustion, anger and urgency take over.','युद्ध के अंतिम चरण में शल्य बची हुई कौरव सेना का नेतृत्व करते हैं। सेना के पतन से कथा भीम और दुर्योधन के गदा-युद्ध तक जाती है। उस मुकाबले के तरीके पर विवाद विजय को सरल उत्सव नहीं बनने देते। थकान, क्रोध और जल्दबाज़ी हावी हों तो तय नियमों का क्या होता है, यह प्रश्न बना रहता है।'],
    [['Shalya','Bhima','Duryodhana','Balarama','Krishna'],['शल्य','भीम','दुर्योधन','बलराम','कृष्ण']],
    [['The end of war','Rules under pressure','Ambiguous victory'],['युद्ध का अंत','दबाव में नियम','जटिल विजय']],
    ['Which rule becomes hardest for you to follow when you feel the end is finally in sight?','जब अंत निकट दिखता है, तब कौन-सा नियम निभाना आपके लिए सबसे कठिन हो जाता है?'],
    pg(9,'Shalya Parva',3,'',[['Shalya Parva, section 58 (Ganguli numbering)','https://www.ibiblio.org/sripedia/ebooks/mb/m09/m09058.htm']])
  ),
  'mahabharata/sauptika':guide(
    ['The main battle is over, but vengeance continues into the night. Ashvatthaman’s attack on the sleeping camp destroys the hope that an exhausted conflict has safely ended. Read this short, violent book alongside the grief that follows it. Its narrative makes a distinction between defeating an opponent and bringing a cycle of harm to a close.','मुख्य युद्ध समाप्त है, लेकिन प्रतिशोध रात में भी जारी रहता है। सोते हुए शिविर पर अश्वत्थामा का आक्रमण इस आशा को तोड़ देता है कि संघर्ष अब सुरक्षित ढंग से समाप्त हो चुका है। इस संक्षिप्त, हिंसक पर्व को अगले पर्व के शोक के साथ पढ़ें। विरोधी को हराना और हानि का चक्र रोकना अलग बातें बनकर सामने आते हैं।'],
    [['Ashvatthaman','Kripa','Kritavarman','Draupadi','Pandavas'],['अश्वत्थामा','कृप','कृतवर्मा','द्रौपदी','पाण्डव']],
    [['Revenge after victory','Vulnerability','Cycles of harm'],['विजय के बाद प्रतिशोध','असुरक्षा','हानि का चक्र']],
    ['What would actually end a conflict, rather than simply give you the last word?','केवल अंतिम बात कहने के बजाय, संघर्ष को वास्तव में समाप्त करने के लिए क्या चाहिए?'],
    pg(10,'Sauptika Parva',3,'',[['Sauptika Parva, section 1 (Ganguli numbering)','https://sacred-texts.com/hin/m10/m10001.htm']])
  ),
  'mahabharata/stri':guide(
    ['The battlefield is now seen through mourning. Gandhari, Kunti, Draupadi and other bereaved relatives confront the cost that military accounts cannot contain. Grief crosses the division between the two sides. This book changes the reader’s vantage point: the aftermath belongs not only to surviving rulers but also to those whose lives victory has broken.','अब रणभूमि शोक की दृष्टि से दिखाई देती है। गांधारी, कुन्ती, द्रौपदी और अन्य शोकाकुल संबंधी उस कीमत का सामना करते हैं जो युद्ध के विवरणों में पूरी नहीं आती। दुख दोनों पक्षों की सीमाएँ पार करता है। युद्ध का परिणाम केवल बचे शासकों का नहीं, उन लोगों का भी है जिनका जीवन विजय ने तोड़ दिया।'],
    [['Gandhari','Kunti','Draupadi','Dhritarashtra','Krishna'],['गांधारी','कुन्ती','द्रौपदी','धृतराष्ट्र','कृष्ण']],
    [['Mourning','Witnessing loss','Beyond opposing sides'],['शोक','हानि को देखना','पक्षों से आगे']],
    ['Whose experience is missing when you describe a difficult event only in terms of winners and losers?','किसी घटना को केवल हार-जीत में बताएँ तो किसका अनुभव छूट जाता है?'],
    pg(11,'Stri Parva',3,'',[['Stri Parva, section 1 (Ganguli numbering)','https://sacred-texts.com/hin/m11/m11001.htm']])
  ),
  'mahabharata/shanti':guide(
    ['Yudhishthira’s grief after victory opens a long inquiry into how to govern and how to live. Bhishma’s teachings range across rulers’ duties, conduct in distress and liberation, often through embedded stories. This is a many-voiced deliberation rather than a short rulebook. Keep the speaker, situation and competing obligations visible as you move between its discussions.','विजय के बाद युधिष्ठिर का शोक शासन और जीवन पर लंबा विचार आरम्भ करता है। भीष्म के उपदेशों में राजधर्म, संकट में आचरण और मोक्ष आते हैं; अनेक बातें कथाओं के माध्यम से कही जाती हैं। यह छोटी नियमावली नहीं, अनेक स्वरों वाला विमर्श है। वक्ता, परिस्थिति और टकराते कर्तव्यों को ध्यान में रखकर पढ़ें।'],
    [['Yudhishthira','Bhishma','Krishna','Vyasa','Narada'],['युधिष्ठिर','भीष्म','कृष्ण','व्यास','नारद']],
    [['Responsible governance','Dharma in distress','Liberation'],['उत्तरदायी शासन','आपद्धर्म','मोक्ष']],
    ['What responsibility still needs your care even when you wish you could withdraw from it?','जब आप पीछे हटना चाहते हों, तब भी कौन-सी जिम्मेदारी आपकी देखभाल माँगती है?'],
    pg(12,'Shanti Parva',3,'',[['Shanti Parva, section I (Rajadharmanusasana), Ganguli numbering','https://www.ibiblio.org/sripedia/ebooks/mb/m12/m12a001.htm']])
  ),
  'mahabharata/anushasana':guide(
    ['Bhishma’s instruction continues with sustained attention to giving, duties and conduct. Stories and dialogues explore what an action means within relationships and social obligations. Some prescriptions reflect the hierarchy and assumptions of their textual setting; presenting them does not require endorsing them today. Read for the questions they raise as well as the answers they offer.','भीष्म का उपदेश दान, कर्तव्य और आचरण पर आगे बढ़ता है। कथाएँ और संवाद संबंधों तथा सामाजिक जिम्मेदारियों के बीच कर्म का अर्थ खोजते हैं। कुछ निर्देश अपने पाठ-परिवेश की सामाजिक श्रेणियों और मान्यताओं को दर्शाते हैं; उनका परिचय आज उनका समर्थन करना नहीं है। उत्तरों के साथ उनसे उठते प्रश्न भी देखें।'],
    [['Bhishma','Yudhishthira','Krishna','Teachers within the stories'],['भीष्म','युधिष्ठिर','कृष्ण','अंतर्कथाओं के उपदेशक']],
    [['Giving','Conduct','Context-sensitive reading'],['दान','आचरण','संदर्भ-सचेत अध्ययन']],
    ['How could you give in a way that attends to the recipient’s needs rather than your own image?','आप ऐसा दान कैसे दे सकते हैं जिसका केंद्र आपकी छवि के बजाय पाने वाले की ज़रूरत हो?'],
    pg(13,'Anushasana Parva',4)
  ),
  'mahabharata/ashvamedhika':guide(
    ['After the war and Bhishma’s death, Yudhishthira’s kingship is consolidated through the horse sacrifice and Arjuna’s journey. The book also contains the Anugita, a later conversation involving Krishna and Arjuna. Ritual, political authority and renewed instruction sit together here. Notice that restoring public order does not automatically settle the inner consequences of the war.','युद्ध और भीष्म की मृत्यु के बाद अश्वमेध तथा अर्जुन की यात्रा के माध्यम से युधिष्ठिर की राजसत्ता और सुदृढ़ होती है। इसी पर्व में कृष्ण और अर्जुन से जुड़ा बाद का संवाद, अनुगीता, भी है। अनुष्ठान, राजसत्ता और फिर से मिलने वाला उपदेश साथ आते हैं। सार्वजनिक व्यवस्था लौटने से युद्ध के भीतर रह गए परिणाम अपने आप समाप्त नहीं होते।'],
    [['Yudhishthira','Arjuna','Krishna','Vyasa'],['युधिष्ठिर','अर्जुन','कृष्ण','व्यास']],
    [['Rebuilding','Ritual and authority','Returning to learning'],['पुनर्निर्माण','अनुष्ठान और अधिकार','सीख की ओर लौटना']],
    ['After a major effort ends, what still needs repair rather than celebration?','बड़ा प्रयास पूरा होने पर किस बात को उत्सव से अधिक सुधार की ज़रूरत रहती है?'],
    pg(14,'Ashvamedhika Parva',4,'',[['Ashvamedhika Parva, section I (Ganguli numbering)','https://www.ibiblio.org/sripedia/ebooks/mb/m14/m14001.htm']])
  ),
  'mahabharata/ashramavasika':guide(
    ['Years after the war, Dhritarashtra and Gandhari leave court for the forest, accompanied by Kunti. The story follows ageing, renunciation and the bonds between survivors who once stood on opposing sides. Care does not erase memory or grief. This quieter book makes room for departures that happen long after the dramatic end of a conflict.','युद्ध के वर्षों बाद धृतराष्ट्र और गांधारी राजमहल छोड़कर वन जाते हैं; कुन्ती भी साथ जाती हैं। कथा वृद्धावस्था, त्याग और कभी विरोधी पक्षों में रहे बचे लोगों के संबंधों को देखती है। देखभाल से स्मृति या शोक मिट नहीं जाते। यह शांत पर्व संघर्ष के बड़े अंत के बहुत बाद होने वाली विदाइयों को जगह देता है।'],
    [['Dhritarashtra','Gandhari','Kunti','Vidura','Yudhishthira'],['धृतराष्ट्र','गांधारी','कुन्ती','विदुर','युधिष्ठिर']],
    [['Ageing','Renunciation','Care after conflict'],['वृद्धावस्था','त्याग','संघर्ष के बाद देखभाल']],
    ['How can you offer care while respecting another person’s wish to choose a different way of life?','किसी के अलग जीवन-मार्ग चुनने का सम्मान करते हुए आप उसकी देखभाल कैसे कर सकते हैं?'],
    pg(15,'Ashramavasika Parva',4,'',[['Ashramavasika Parva, section I (Ganguli numbering)','https://sacred-texts.com/hin/m15/m15001.htm']])
  ),
  'mahabharata/mausala':guide(
    ['The destruction of Krishna’s clan brings another ending after the Kurukshetra war. An iron implement, a curse and a violent quarrel belong to the narrative of that collapse. Krishna’s departure and the survivors’ vulnerability unsettle any idea that earlier success guarantees lasting security. Read the book as an account of an age passing, not a formula for predicting misfortune.','कुरुक्षेत्र युद्ध के बाद कृष्ण के कुल का विनाश एक और अंत लाता है। लोहे का अस्त्र, शाप और हिंसक कलह इस पतन की कथा का हिस्सा हैं। कृष्ण का प्रस्थान और बचे लोगों की असुरक्षा बताते हैं कि पुरानी सफलता स्थायी सुरक्षा की गारंटी नहीं है। इसे युग के बीतने की कथा की तरह पढ़ें, अनिष्ट की भविष्यवाणी के सूत्र की तरह नहीं।'],
    [['Krishna','Balarama','Samba','Arjuna','Yadava clans'],['कृष्ण','बलराम','साम्ब','अर्जुन','यादव कुल']],
    [['An age ending','Collective destruction','Impermanence'],['युग का अंत','सामूहिक विनाश','अनित्यता']],
    ['What support would remain useful if a familiar source of strength were no longer available?','शक्ति का कोई परिचित सहारा न रहे तो कौन-सा सहयोग उपयोगी बना रहेगा?'],
    pg(16,'Mausala Parva',4,'',[['Mausala Parva, section 1 (Ganguli numbering)','https://sacred-texts.com/hin/m16/m16001.htm']])
  ),
  'mahabharata/mahaprasthanika':guide(
    ['The Pandavas and Draupadi leave royal life and begin their final journey. As companions fall away, the story turns from possession and achievement toward what Yudhishthira refuses to abandon. His insistence on keeping faith with a following dog becomes a decisive test. The ending invites reflection on care that is not traded for personal reward.','पाण्डव और द्रौपदी राजजीवन छोड़कर अंतिम यात्रा पर निकलते हैं। साथियों के बिछुड़ने के साथ कथा संपत्ति और उपलब्धि से हटकर उस बात पर आती है जिसे युधिष्ठिर छोड़ने को तैयार नहीं हैं। साथ चल रहे कुत्ते के प्रति उनकी निष्ठा निर्णायक परीक्षा बनती है। यह अंत ऐसे संरक्षण पर विचार कराता है जिसका निजी पुरस्कार से सौदा न हो।'],
    [['Yudhishthira','Draupadi','Pandavas','Indra','Dharma'],['युधिष्ठिर','द्रौपदी','पाण्डव','इन्द्र','धर्म']],
    [['Letting go','Fidelity','Compassion without reward'],['त्याग','निष्ठा','पुरस्कार से परे करुणा']],
    ['What commitment to another being would you keep even if it cost you an attractive reward?','किसी जीव के प्रति कौन-सी जिम्मेदारी आप आकर्षक पुरस्कार खोकर भी निभाएँगे?'],
    pg(17,'Mahaprasthanika Parva',4,'',[['Mahaprasthanika Parva, section 3 (Ganguli numbering)','https://sacred-texts.com/hin/m17/m17003.htm']])
  ),
  'mahabharata/svargarohana':guide(
    ['Yudhishthira’s arrival in heaven does not immediately resolve his questions. Seeing Duryodhana honoured and failing to find his loved ones challenges his expectations of justice. Further trials and recognition bring the epic toward its close. Its final movement asks readers to examine attachment, judgment and belonging without reducing the whole story to a simple tally of rewards.','स्वर्ग पहुँचने पर भी युधिष्ठिर के प्रश्न तुरंत समाप्त नहीं होते। दुर्योधन का सम्मान और अपने प्रियजनों का न दिखना न्याय की उनकी अपेक्षा को चुनौती देता है। आगे की परीक्षाएँ और पहचान महाकाव्य को समापन तक ले जाती हैं। अंतिम चरण आसक्ति, निर्णय और अपनत्व पर विचार कराता है; पूरी कथा को पुरस्कारों के सरल हिसाब में नहीं समेटता।'],
    [['Yudhishthira','Narada','Indra','Dharma','Pandavas and Draupadi'],['युधिष्ठिर','नारद','इन्द्र','धर्म','पाण्डव और द्रौपदी']],
    [['Justice and appearances','Final testing','Reunion'],['न्याय और दिखाई देने वाला सत्य','अंतिम परीक्षा','पुनर्मिलन']],
    ['When an outcome contradicts your sense of fairness, what questions should come before a final judgment?','कोई परिणाम आपकी न्याय-बुद्धि के विरुद्ध लगे तो अंतिम निर्णय से पहले कौन-से प्रश्न पूछने चाहिए?'],
    pg(18,'Svargarohana Parva',4,'',[['Svargarohana Parva, section 1 (Ganguli numbering)','https://sacred-texts.com/hin/m18/m18001.htm']])
  ),
  'ramayana/bala':guide(
    ['Bala Kanda frames the telling of Rama’s life and introduces the princes of Ayodhya. Rama and Lakshmana accompany Vishvamitra, entering a world of disciplined learning, dangerous encounters, and inherited stories. The journey reaches Mithila, where Rama’s handling of Shiva’s bow leads toward his marriage to Sita. Beginnings here connect family, teaching, and responsibility.','बालकाण्ड रामकथा के कथन की भूमिका रचता है और अयोध्या के राजकुमारों का परिचय देता है। राम और लक्ष्मण विश्वामित्र के साथ जाकर अनुशासित शिक्षा, संकटों और पुरानी कथाओं से परिचित होते हैं। यात्रा मिथिला पहुँचती है, जहाँ राम का शिवधनुष उठाना और तोड़ना सीता से उनके विवाह का मार्ग खोलता है। ये आरंभ परिवार, शिक्षा और उत्तरदायित्व को जोड़ते हैं।'],
    [['Rama','Sita','Lakshmana','Vishvamitra','Dasharatha','Janaka','Valmiki','Narada'],['राम','सीता','लक्ष्मण','विश्वामित्र','दशरथ','जनक','वाल्मीकि','नारद']],
    [['Learning through guidance','Power and responsibility','Family and lineage','The telling of an epic'],['मार्गदर्शन से सीखना','शक्ति और उत्तरदायित्व','परिवार और वंश','महाकाव्य का कथन']],
    ['How does learning from a guide change what a person is ready to take responsibility for?','किसी गुरु से सीखना व्यक्ति की जिम्मेदारी उठाने की तैयारी को कैसे बदलता है?'],
    [src('Valmiki Ramayana, Bala Kanda; M. N. Dutt translation, Volume 1','https://www.gutenberg.org/cache/epub/57265/pg57265-images.html','whole-book bibliographic locator'),src('Bala Kanda, Sarga 22: departure with Vishvamitra','https://www.valmiki.iitk.ac.in/summary?field_kanda_tid=1&field_sarga_value=22'),src('Alternate locator · Dutt Volume 1, Section XXII: departure with Vishvamitra','https://www.gutenberg.org/cache/epub/57265/pg57265-images.html','working edition-labelled alternate; use Section XXII in this volume'),src('Bala Kanda, Sarga 67: the bow at Mithila','https://www.valmiki.iitk.ac.in/summary?field_kanda_tid=1&field_sarga_value=67'),src('Alternate locator · Desiraju Hanumanta Rao, Bala Sarga 67: the bow at Mithila','https://valmikiramayan.net/utf8/baala/sarga67/balaroman67.htm','working edition-labelled alternate')],
    ['This guide follows the Valmiki Ramayana. Tulsidas’s Ramcharitmanas is a distinct work; its similarly named Bala Kanda should not be treated as the same text.','यह परिचय वाल्मीकि रामायण पर आधारित है। तुलसीदास का रामचरितमानस एक अलग कृति है; उसके समान नाम वाले बालकाण्ड को यही पाठ न मानें।']
  ),
  'ramayana/ayodhya':guide(
    ['Preparations for Rama’s consecration become a crisis when Kaikeyi claims Dasharatha’s promised boons. Rama accepts fourteen years in exile, with Sita and Lakshmana accompanying him. Dasharatha’s death deepens the rupture. Bharata seeks Rama’s return, then governs under the sign of his brother’s sandals. The book tests promises against grief, affection, and the responsibilities of rule.','राम के राज्याभिषेक की तैयारी संकट में बदल जाती है जब कैकेयी दशरथ के दिए वरदान माँगती हैं। राम चौदह वर्ष का वनवास स्वीकार करते हैं और सीता तथा लक्ष्मण उनके साथ जाते हैं। दशरथ की मृत्यु शोक को और गहरा करती है। भरत राम को लौटाना चाहते हैं, फिर उनकी पादुकाओं को शासन का प्रतीक बनाते हैं। यहाँ वचन, स्नेह और राजधर्म कठिन परीक्षा से गुजरते हैं।'],
    [['Rama','Sita','Lakshmana','Bharata','Dasharatha','Kaikeyi','Kausalya','Guha'],['राम','सीता','लक्ष्मण','भरत','दशरथ','कैकेयी','कौसल्या','गुह']],
    [['Promises and their consequences','Love between siblings','Grief and separation','Rule held in trust'],['वचन और उनके परिणाम','भ्रातृस्नेह','शोक और वियोग','धरोहर के रूप में शासन']],
    ['When duties conflict, how can loyalty include care for the people who bear the cost?','जब कर्तव्य आपस में टकराएँ, तब निष्ठा में उन लोगों की देखभाल कैसे शामिल हो सकती है जो उसका मूल्य चुकाते हैं?'],
    [src('Valmiki Ramayana, Ayodhya Kanda; M. N. Dutt translation, Volume 1','https://www.gutenberg.org/cache/epub/57265/pg57265-images.html','whole-book bibliographic locator'),src('Ayodhya Kanda, Sarga 112: Rama entrusts his sandals to Bharata','https://www.valmiki.iitk.ac.in/summary?field_kanda_tid=2&field_sarga_value=112'),src('Alternate locator · K. M. K. Murthy, Ayodhya Sarga 112: Rama’s sandals','https://www.valmikiramayan.net/utf8/ayodhya/sarga112/ayodhyaroman112.htm','working edition-labelled alternate')],
    ['The sandal episode is located using the named editions, whose numbering should be checked separately. This is a guide to Valmiki’s Ayodhya Kanda.','पादुका-प्रसंग के लिए नामित संस्करणों के संदर्भ दिए गए हैं; उनकी क्रम-संख्या अलग से जाँचें। यह वाल्मीकि के अयोध्याकाण्ड का परिचय है।']
  ),
  'ramayana/aranya':guide(
    ['Forest exile brings encounters with ascetics, rakshasas, and vulnerable lives beyond the palace. Conflict at Panchavati escalates through Shurpanakha, Khara, and Ravana. Maricha’s deceptive deer draws Rama away, and Ravana abducts Sita. Jatayu resists him; Rama and Lakshmana begin their anguished search. The forest becomes a setting for courage, loss, and the difficulty of judging appearances.','वनवास में राजमहल से दूर ऋषियों, राक्षसों और असुरक्षित जीवनों से भेंट होती है। पंचवटी का संघर्ष शूर्पणखा, खर और रावण तक फैलता है। मारीच का मायावी मृग राम को दूर ले जाता है और रावण सीता का हरण करता है। जटायु उसका प्रतिरोध करते हैं; राम और लक्ष्मण व्याकुल होकर खोज शुरू करते हैं। वन साहस, वियोग और बाहरी रूप को परखने की कठिनाई का स्थल बनता है।'],
    [['Rama','Sita','Lakshmana','Shurpanakha','Maricha','Ravana','Jatayu','Shabari'],['राम','सीता','लक्ष्मण','शूर्पणखा','मारीच','रावण','जटायु','शबरी']],
    [['Deception and discernment','Protection of the vulnerable','Grief and perseverance','Escalating conflict'],['छल और विवेक','असुरक्षित लोगों की रक्षा','शोक और धैर्य','बढ़ता हुआ संघर्ष']],
    ['What helps us respond to another person’s suffering without allowing fear or anger to decide everything?','दूसरे के दुःख का उत्तर देते समय भय या क्रोध को हर निर्णय पर हावी होने से कैसे रोक सकते हैं?'],
    [src('Valmiki Ramayana, Aranya Kanda; M. N. Dutt translation, Volume 2','https://www.gutenberg.org/cache/epub/57826/pg57826-images.html','whole-book bibliographic locator'),src('Aranya Kanda, Sarga 51: Jatayu’s resistance to Ravana','https://www.valmiki.iitk.ac.in/summary?field_kanda_tid=3&field_sarga_value=51'),src('Alternate locator · ValmikiRamayan.net, Aranya Sarga 51: Jatayu’s resistance','https://www.valmikiramayan.net/utf8/aranya/sarga51/aranyaroman51.htm','working edition-labelled alternate')],
    ['Later retellings may supply details not established by these citations; this guide follows the linked Valmiki narrative.','बाद की पुनर्कथाओं के सभी विवरण इन संदर्भों से प्रमाणित नहीं होते; यह परिचय दिए गए वाल्मीकि-पाठ का अनुसरण करता है।']
  ),
  'ramayana/kishkindha':guide(
    ['Hanuman brings Rama and Lakshmana into contact with Sugriva, whose conflict with Vali shapes a new alliance. Vali’s death raises searching questions about justice and force, while Tara’s counsel and grief deserve attention. After delays, Sugriva organizes the search for Sita. The southern search party reaches the ocean, where Hanuman’s capacity becomes central to the next step.','हनुमान राम और लक्ष्मण को सुग्रीव से मिलाते हैं, जिनका बालि से संघर्ष नई मित्रता की दिशा तय करता है। बालि की मृत्यु न्याय और बल के प्रयोग पर गहरे प्रश्न उठाती है; तारा की सलाह और शोक भी ध्यान माँगते हैं। विलंब के बाद सुग्रीव सीता की खोज का आयोजन करते हैं। दक्षिण का खोज-दल समुद्र तक पहुँचता है, जहाँ आगे का कदम हनुमान की सामर्थ्य पर निर्भर होता है।'],
    [['Rama','Lakshmana','Hanuman','Sugriva','Vali','Tara','Angada','Jambavan','Sampati'],['राम','लक्ष्मण','हनुमान','सुग्रीव','बालि','तारा','अंगद','जाम्बवान','सम्पाति']],
    [['Friendship and reciprocal obligations','Justice and the use of force','Listening to counsel','Collective effort'],['मित्रता और पारस्परिक दायित्व','न्याय और बल का प्रयोग','सलाह सुनना','सामूहिक प्रयास']],
    ['How should a promise between friends be tested against the needs and rights of others?','मित्रों के बीच किए वचन को दूसरों की जरूरतों और अधिकारों की कसौटी पर कैसे परखें?'],
    [src('Valmiki Ramayana, Kishkindha Kanda; M. N. Dutt translation, Volume 2','https://www.gutenberg.org/cache/epub/57826/pg57826-images.html','whole-book bibliographic locator'),src('Kishkindha Kanda, Sarga 9: Sugriva’s account of the dispute','https://www.valmiki.iitk.ac.in/sloka?field_kanda_tid=4&field_sarga_value=9&language=ro')],
    ['Vali is often written Bali in Hindi; the spelling difference identifies the same character. Interpretations of his death should be distinguished from the narrative.','अंग्रेज़ी में Vali और हिंदी में बालि यहाँ एक ही पात्र के नाम हैं। उनकी मृत्यु की व्याख्याओं को मूल कथानक से अलग पहचानें।']
  ),
  'ramayana/sundara':guide(
    ['Sundara Kanda follows Hanuman across the ocean and through Lanka in search of Sita. His meeting with her turns uncertain hope into communication: Rama’s ring establishes trust, and Sita sends a token and message in return. Confrontation, capture, and the burning of Lanka follow. Hanuman’s return carries both reassurance and practical knowledge for the rescue ahead.','सुन्दरकाण्ड में हनुमान समुद्र पार करके लंका में सीता की खोज करते हैं। उनसे मिलकर अनिश्चित आशा संवाद में बदलती है: राम की मुद्रिका विश्वास जगाती है और सीता प्रत्युत्तर में पहचान-चिह्न तथा संदेश देती हैं। इसके बाद संघर्ष, बंधन और लंका-दहन के प्रसंग आते हैं। हनुमान लौटकर आश्वासन के साथ सीता को छुड़ाने के लिए उपयोगी जानकारी भी लाते हैं।'],
    [['Hanuman','Sita','Ravana','Trijata','Vibhishana','Rama'],['हनुमान','सीता','रावण','त्रिजटा','विभीषण','राम']],
    [['Devotion expressed through service','Trust and careful communication','Courage with discernment','Hope amid captivity'],['सेवा में व्यक्त भक्ति','विश्वास और सावधान संवाद','विवेकपूर्ण साहस','बंदी जीवन में आशा']],
    ['What makes reassurance trustworthy when someone is isolated and afraid?','जब कोई अकेला और भयभीत हो, तब आश्वासन को भरोसेमंद क्या बनाता है?'],
    [src('Valmiki Ramayana, Sundara Kanda; M. N. Dutt translation, Volume 2','https://www.gutenberg.org/cache/epub/57826/pg57826-images.html','whole-book bibliographic locator'),src('Sundara Kanda, Sarga 26: Sita’s distress in captivity','https://www.valmiki.iitk.ac.in/summary?field_kanda_tid=5&field_sarga_value=26'),src('Alternate locator · Dutt Volume 2, Section XXVI: Sita in captivity','https://www.gutenberg.org/cache/epub/57826/pg57826-images.html','working edition-labelled alternate; use Section XXVI in this volume')],
    ['Valmiki’s Sundara Kanda and Tulsidas’s Sundarkand belong to distinct works with different verse forms and reference systems.','वाल्मीकि का सुन्दरकाण्ड और तुलसीदास का सुन्दरकाण्ड अलग कृतियों के अंश हैं; उनके छंद और संदर्भ-पद्धतियाँ भिन्न हैं।']
  ),
  'ramayana/yuddha':guide(
    ['The alliance crosses the sea and confronts Ravana’s forces in Lanka. Vibhishana’s change of allegiance, the labor of building the bridge, and the losses of battle show the many decisions behind victory. Ravana falls, but reunion includes Sita’s painful ordeal by fire. The return to Ayodhya and Rama’s consecration close this book’s movement from separation toward restoration.','मित्र-सेना समुद्र पार करके लंका में रावण की सेना से युद्ध करती है। विभीषण का पक्ष बदलना, सेतु-निर्माण का श्रम और युद्ध की हानियाँ विजय के पीछे के अनेक निर्णय दिखाते हैं। रावण मारा जाता है, पर पुनर्मिलन में सीता की पीड़ादायक अग्निपरीक्षा भी आती है। अयोध्या-वापसी और राम का राज्याभिषेक इस काण्ड की वियोग से पुनर्स्थापना तक की यात्रा को पूर्ण करते हैं।'],
    [['Rama','Sita','Lakshmana','Hanuman','Vibhishana','Ravana','Kumbhakarna','Indrajit','Nala'],['राम','सीता','लक्ष्मण','हनुमान','विभीषण','रावण','कुम्भकर्ण','इन्द्रजित','नल']],
    [['Counsel and allegiance','Cooperation under pressure','The human cost of conflict','Victory and accountability'],['परामर्श और पक्ष-चयन','संकट में सहयोग','संघर्ष की मानवीय कीमत','विजय और जवाबदेही']],
    ['What remains to be repaired after a conflict has been won?','संघर्ष जीत लेने के बाद भी किन घावों और संबंधों को सँवारना बाकी रहता है?'],
    [src('Valmiki Ramayana, Yuddha Kanda; M. N. Dutt translation, Volume 3','https://www.gutenberg.org/cache/epub/60188/pg60188-images.html','whole-book bibliographic locator'),src('Yuddha Kanda, Sarga 130: preparations for Rama’s reception at Ayodhya','https://www.valmiki.iitk.ac.in/sloka?field_kanda_tid=6&field_sarga_value=130&language=dv'),src('Alternate locator · Hari Prasad Shastri, Yuddha Kanda, Chapter 130','https://www.wisdomlib.org/hinduism/book/the-ramayana-of-valmiki/d/doc424759.html','working edition-labelled alternate')],
    ['Yuddha Kanda is the Valmiki title used here; Tulsidas’s corresponding war book is Lanka Kanda, and their numbering is not interchangeable.','यहाँ वाल्मीकि-संस्करण का नाम युद्धकाण्ड है; तुलसीदास की कृति में प्रमुख युद्ध-भाग लंकाकाण्ड है और उनकी क्रम-संख्या परस्पर बदलने योग्य नहीं।']
  ),
  'ramayana/uttara':guide(
    ['Uttara Kanda looks backward to Ravana’s origins and forward to Rama’s reign. Public suspicion leads to Sita’s abandonment; Valmiki shelters her, and Lava and Kusha become bearers of the epic’s song. Sita’s return to the earth and the closing of Rama’s earthly life accompany difficult episodes of kingship, including Shambuka’s death, inviting careful attention to suffering and authority.','उत्तरकाण्ड रावण के अतीत और राम के शासनकाल, दोनों की ओर देखता है। लोकापवाद के कारण सीता का परित्याग होता है; वाल्मीकि उन्हें आश्रय देते हैं और लव-कुश रामकथा का गायन करते हैं। सीता का पृथ्वी में समाना और राम के पृथ्वी-जीवन का समापन, शम्बूक-वध जैसे कठिन राजकीय प्रसंगों के साथ आते हैं। यह कथा पीड़ा और सत्ता पर संवेदनशील विचार माँगती है।'],
    [['Rama','Sita','Valmiki','Lava','Kusha','Agastya','Shambuka'],['राम','सीता','वाल्मीकि','लव','कुश','अगस्त्य','शम्बूक']],
    [['Public reputation and personal suffering','Kingship and exclusion','Memory carried through storytelling','Separation and closure'],['लोकप्रतिष्ठा और व्यक्तिगत पीड़ा','राजसत्ता और बहिष्करण','कथन के माध्यम से स्मृति','वियोग और समापन']],
    ['How can we read a revered story attentively while also hearing the pain of those harmed within it?','किसी आदरणीय कथा को ध्यान से पढ़ते हुए उसके भीतर आहत लोगों की पीड़ा को भी कैसे सुनें?'],
    [src('Valmiki Ramayana, Uttara Kanda; M. N. Dutt translation, Volume 4','https://www.gutenberg.org/cache/epub/62496/pg62496-images.html','whole-book bibliographic locator'),src('Goldman and Goldman, The Ramayana of Valmiki, Volume VII, introduction','https://www.jstor.org/stable/j.ctt1gsmwj0'),src('Goldman and Goldman, Volume VII, introduction excerpt','https://assets.press.princeton.edu/chapters/i10906.pdf')],
    ['Uttara Kanda belongs to the received seven-book Valmiki tradition, while scholars identify later compositional layers and variation. This guide does not settle those debates or equate it with Tulsidas’s Uttarakand.','उत्तरकाण्ड प्रचलित सात-काण्ड परंपरा का भाग है, जबकि विद्वान बाद के रचनात्मक स्तर और पाठ-भिन्नताएँ पहचानते हैं। यह परिचय विवादों का निर्णय नहीं करता और इसे तुलसीदास के उत्तरकाण्ड के समान नहीं मानता।']
  ),
  'shiva/vidyeshvara':guide(
    ['Vidyeshvara introduces a way of approaching Shiva through attentive listening, worship, and reflection. The unbounded column of fire interrupts Brahma and Vishnu’s rivalry, challenging confidence in status and measurement. Discussions of the linga, sacred sound, conduct, and offerings then connect that encounter with a sustained devotional life.','विद्येश्वर संहिता श्रवण, पूजा और मनन के माध्यम से शिव की ओर बढ़ने का मार्ग प्रस्तुत करती है। असीम अग्निस्तंभ ब्रह्मा और विष्णु की स्पर्धा को रोकता है तथा पद और माप पर आधारित विश्वास को चुनौती देता है। आगे लिंग, पवित्र ध्वनि, आचरण और अर्पण की चर्चा इस प्रसंग को नियमित भक्तिमय जीवन से जोड़ती है।'],
    [['Shiva','Brahma and Vishnu','Suta and the listening sages'],['शिव','ब्रह्मा और विष्णु','सूत और श्रोता ऋषि']],
    [['Humility before the immeasurable','Listening and reflection','Linga worship','Mantra and devotional discipline'],['असीम के सामने विनम्रता','श्रवण और मनन','लिंग-पूजा','मंत्र और भक्ति का अनुशासन']],
    ['When certainty becomes rivalry, what would honest acknowledgment of your limits make possible?','जब अपना विश्वास स्पर्धा बन जाए, तब अपनी सीमाएँ ईमानदारी से स्वीकार करने पर क्या बदल सकता है?'],
    [src('Shiva Purana, Vidyeshvara-samhita, section index','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc225543.html'),src('Shiva Purana 1.7, especially verses 10–33','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc225552.html'),src('Shiva Purana 1.17, especially verses 27–35','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc225562.html')],
    ['References follow this seven-samhita edition. Its traditional account of an earlier twelve-samhita text should not be merged with this arrangement.','संहिता और अध्याय के संकेत इस सात-संहिता वाले संस्करण के अनुसार हैं। पूर्ववर्ती बारह-संहिता ग्रंथ के पारंपरिक विवरण को इस व्यवस्था के साथ एक नहीं मानना चाहिए।']
  ),
  'shiva/rudra':guide(
    ['Rudra is the expansive narrative heart of this edition. Creation stories lead into Sati’s conflict with Daksha, Parvati’s devotion and marriage, the stories of Karttikeya and Ganesha, and battles involving Shiva. Read across these changing settings, the section explores attachment, power, loss, reconciliation, and the relationship between ascetic life and family.','इस संस्करण में रुद्र संहिता विस्तृत कथाओं का प्रमुख केंद्र है। सृष्टि-वर्णन के बाद दक्ष के साथ सती का संघर्ष, पार्वती की भक्ति और विवाह, कार्तिकेय तथा गणेश की कथाएँ और शिव से जुड़े युद्ध आते हैं। इन बदलते प्रसंगों में आसक्ति, शक्ति, वियोग, मेल-मिलाप तथा तपस्वी और पारिवारिक जीवन के संबंध पर विचार किया जा सकता है।'],
    [['Shiva','Sati and Parvati','Daksha','Karttikeya and Ganesha','Brahma and Narada'],['शिव','सती और पार्वती','दक्ष','कार्तिकेय और गणेश','ब्रह्मा और नारद']],
    [['Creation and divine presence','Devotion and perseverance','Family, loss, and reconciliation','Power and responsibility'],['सृष्टि और दिव्य उपस्थिति','भक्ति और दृढ़ता','परिवार, वियोग और मेल-मिलाप','शक्ति और उत्तरदायित्व']],
    ['Which episode makes you reconsider how devotion, responsibility, and pride can coexist in a person?','कौन-सा प्रसंग आपको यह सोचने पर विवश करता है कि एक व्यक्ति में भक्ति, उत्तरदायित्व और अहंकार कैसे साथ रह सकते हैं?'],
    [src('Shiva Purana 2.1, Srishti-khanda index','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc225966.html'),src('Shiva Purana 2.2, Sati-khanda index','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226019.html'),src('Shiva Purana 2.3, Parvati-khanda index','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226064.html'),src('Shiva Purana 2.4, Kumara-khanda index','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226120.html'),src('Shiva Purana 2.5, Yuddha-khanda index','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226141.html')],
    ['Rudra contains five khandas: Srishti, Sati, Parvati, Kumara, and Yuddha. Chapter numbering restarts in each, so a citation must name its khanda.','रुद्र संहिता में पाँच खंड हैं: सृष्टि, सती, पार्वती, कुमार और युद्ध। हर खंड में अध्यायों की गणना फिर शुरू होती है, इसलिए अध्याय के साथ खंड का नाम देना आवश्यक है।']
  ),
  'shiva/shatarudra':guide(
    ['Shatarudra gathers many manifestations of Shiva, moving between cosmic forms and encounters within particular lives. Its eightfold presentation links divine presence with the world and its beings. Stories such as Arjuna’s meeting with the hunter Kirata invite readers to question appearances and consider how recognition, testing, and grace reshape devotion.','शतरुद्र संहिता शिव के अनेक प्रकट रूपों को समेटती है और विराट रूपों से विशेष जीवन-प्रसंगों तक जाती है। अष्टमूर्ति-वर्णन दिव्य उपस्थिति को जगत और उसके प्राणियों से जोड़ता है। अर्जुन और किरात का मिलन बाहरी रूप पर प्रश्न करने तथा पहचान, परीक्षा और कृपा से भक्ति में आने वाले परिवर्तन पर सोचने का अवसर देता है।'],
    [['Shiva in many forms','Nandishvara','Arjuna','Kirata'],['अनेक रूपों में शिव','नंदीश्वर','अर्जुन','किरात']],
    [['One divine presence, many manifestations','Reverence for living beings','Recognition beyond appearances','Devotion tested and renewed'],['एक दिव्य उपस्थिति, अनेक रूप','जीवों के प्रति आदर','बाहरी रूप से आगे की पहचान','भक्ति की परीक्षा और नवीकरण']],
    ['What changes in your treatment of others when reverence extends beyond a familiar sacred image?','जब श्रद्धा किसी परिचित पवित्र प्रतिमा से आगे बढ़ती है, तब दूसरों के प्रति आपके व्यवहार में क्या परिवर्तन आता है?'],
    [src('Shiva Purana, Shatarudra-samhita, section index','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226396.html'),src('Shiva Purana 3.2, especially verses 2–16','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226398.html'),src('Shiva Purana 3.41, especially verses 15–26','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226437.html')],
    ['The named manifestations follow this Shaiva text and should be read within its devotional perspective.','यहाँ उल्लिखित प्रकट रूप इस शैव ग्रंथ के अनुसार हैं और इन्हें इसी भक्ति-दृष्टि में पढ़ना चाहिए।']
  ),
  'shiva/kotirudra':guide(
    ['Kotirudra connects worship with sacred places, remembered stories, and observances. Accounts of lingas and jyotirlingas show how devotion gives a place religious meaning; Rama’s prayer at the shore is one example. The Shivaratri narratives shift attention toward transformation, while closing discussions connect devotional practice with questions about liberation and knowledge.','कोटिरुद्र संहिता पूजा को पवित्र स्थानों, उनसे जुड़ी कथाओं और व्रतों से जोड़ती है। लिंगों और ज्योतिर्लिंगों के प्रसंग बताते हैं कि भक्ति किसी स्थान को धार्मिक अर्थ कैसे देती है; समुद्रतट पर राम की प्रार्थना इसका एक उदाहरण है। शिवरात्रि की कथाएँ परिवर्तन की ओर ध्यान ले जाती हैं, और अंतिम चर्चाएँ साधना को मुक्ति तथा ज्ञान के प्रश्नों से जोड़ती हैं।'],
    [['Shiva','Rama','Suta','Gurudruha, the hunter in the Shivaratri narrative'],['शिव','राम','सूत','शिवरात्रि की कथा का व्याध गुरुद्रुह']],
    [['Sacred place and remembered story','Jyotirlinga traditions','Shivaratri observance','Devotion, knowledge, and liberation'],['पवित्र स्थान और उससे जुड़ी कथा','ज्योतिर्लिंग परंपराएँ','शिवरात्रि का व्रत','भक्ति, ज्ञान और मुक्ति']],
    ['What makes a place sacred in your experience: its story, your attention, the community, or a meeting of these?','आपके अनुभव में किसी स्थान को पवित्र क्या बनाता है: उसकी कथा, आपका ध्यान, समुदाय या इन सबका मेल?'],
    [src('Shiva Purana, Kotirudra-samhita, section index','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226439.html'),src('Shiva Purana 4.31, especially verses 21–40','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226532.html'),src('Shiva Purana 4.40, Shivaratri hunter narrative','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226541.html')],
    ['These are the text’s sacred-place narratives; this guide does not resolve present-day claims about the geographical identity of particular shrines.','ये ग्रंथ में वर्णित पवित्र स्थलों की कथाएँ हैं; यह मार्गदर्शिका किसी तीर्थ की वर्तमान भौगोलिक पहचान से जुड़े दावों का निर्णय नहीं करती।']
  ),
  'shiva/uma':guide(
    ['Uma places human conduct within a broad sacred world of actions, consequences, cosmic regions, lineages, and manifestations of the Goddess. Amid its varied material, the praise of feeding others and the story of Shatakshi responding to drought offer a clear reading thread: care for vulnerable life belongs alongside reflection on ultimate questions.','उमा संहिता मानव आचरण को कर्म, फल, लोकों, वंशावलियों और देवी के प्रकट रूपों वाले व्यापक धार्मिक जगत में रखती है। इसकी विविध सामग्री में अन्नदान की प्रशंसा और सूखे से पीड़ित जगत पर शताक्षी की करुणा एक उपयोगी सूत्र देती हैं: जीवन के गहन प्रश्नों पर विचार के साथ असहाय प्राणियों की देखभाल भी महत्त्वपूर्ण है।'],
    [['Uma and other manifestations of the Goddess','Shatakshi','Vyasa','Sanatkumara','Suta'],['उमा और देवी के अन्य प्रकट रूप','शताक्षी','व्यास','सनत्कुमार','सूत']],
    [['Actions and consequences','Food, generosity, and care','Cosmology and lineages','The Goddess as sustainer'],['कर्म और उनके फल','अन्न, दान और सेवा','सृष्टि-विचार और वंशावलियाँ','पालन करने वाली देवी']],
    ['What concrete act of nourishment or care could accompany your study of this section?','इस संहिता के अध्ययन के साथ आप पोषण या देखभाल का कौन-सा ठोस कार्य जोड़ सकते हैं?'],
    [src('Shiva Purana, Uma-samhita, section index','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226545.html'),src('Shiva Purana 5.11, especially verses 17–25','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226556.html'),src('Shiva Purana 5.50, especially verses 7–23','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226610.html')],
    ['Cosmological descriptions and social prescriptions belong to the text’s historical religious setting; this overview does not endorse every prescription for present-day life.','ब्रह्मांड के वर्णन और सामाजिक विधान ग्रंथ के ऐतिहासिक धार्मिक परिवेश से जुड़े हैं; यह परिचय हर विधान को आज का नियम मानकर समर्थन नहीं करता।']
  ),
  'shiva/kailasa':guide(
    ['Kailasa turns toward sustained inquiry and the disciplines of renunciation. Uma asks Shiva about pranava, sacred sound, and the purpose of practice; other dialogues explore consciousness and Shiva’s non-dual nature. Ritual detail and philosophical questioning sit together, inviting readers to notice how instruction, interpretation, and lived discipline depend on one another.','कैलास संहिता गहन जिज्ञासा और संन्यास के अनुशासन की ओर मुड़ती है। उमा शिव से प्रणव, पवित्र ध्वनि और साधना के उद्देश्य के बारे में पूछती हैं; अन्य संवाद चेतना और शिव के अद्वैत स्वरूप पर विचार करते हैं। अनुष्ठान के विवरण और दार्शनिक प्रश्न साथ आते हैं, जिससे शिक्षा, अर्थबोध और जीवन में अनुशासन के पारस्परिक संबंध दिखाई देते हैं।'],
    [['Shiva','Uma','Vamadeva','Subrahmanya (Skanda)'],['शिव','उमा','वामदेव','सुब्रह्मण्य (स्कंद)']],
    [['Pranava and interpretation','Renunciation and daily discipline','Teacher–student inquiry','Shaiva non-duality'],['प्रणव और उसका अर्थ','संन्यास और दैनिक अनुशासन','गुरु-शिष्य की जिज्ञासा','शैव अद्वैत']],
    ['Which practice do you understand more deeply when you ask about its meaning rather than only its procedure?','किस साधना का केवल क्रम जानने के बजाय उसका अर्थ पूछने से आपकी समझ अधिक गहरी होती है?'],
    [src('Shiva Purana, Kailasa-samhita, section index','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226612.html'),src('Shiva Purana 6.2, especially verses 21–29','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226614.html'),src('Shiva Purana 6.17, especially verses 1–7','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226629.html')],
    ['The rites here often address initiated renunciants. This guide is not an initiation manual or a substitute for qualified instruction.','यहाँ के अनुष्ठान प्रायः दीक्षित संन्यासियों से संबंधित हैं। यह मार्गदर्शिका दीक्षा-विधि की पुस्तिका या योग्य आचार्य के मार्गदर्शन का विकल्प नहीं है।']
  ),
  'shiva/vayaviya':guide(
    ['Vayaviya brings narrative, Shaiva teaching, and practice into a concluding synthesis. Vayu addresses the sages, while dialogues involving Upamanyu and Krishna explore Shiva’s relationship to the world, bondage, devotion, and yoga. The section invites a connected reading of knowledge and practice: understanding develops alongside attention, ethical restraint, and guidance.','वायवीय संहिता कथा, शैव तत्त्वचिंतन और साधना को अंतिम समन्वय में लाती है। वायु ऋषियों से संवाद करते हैं, जबकि उपमन्यु और कृष्ण के संवादों में जगत से शिव के संबंध, बंधन, भक्ति और योग की चर्चा होती है। इसे ज्ञान और साधना को साथ रखकर पढ़ा जा सकता है: समझ ध्यान, नैतिक संयम और मार्गदर्शन के साथ विकसित होती है।'],
    [['Vayu and the sages','Upamanyu','Krishna','Śiva and Śivā'],['वायु और ऋषि','उपमन्यु','कृष्ण','शिव और शिवा']],
    [['Shiva, the world, and the bound soul','Devotion and understanding','Guided practice','Yoga and restraint'],['शिव, जगत और बंधनग्रस्त जीव','भक्ति और बोध','मार्गदर्शन में साधना','योग और संयम']],
    ['How might study, care for others, and regular attention strengthen one another in your life?','आपके जीवन में अध्ययन, दूसरों की देखभाल और नियमित एकाग्रता एक-दूसरे को कैसे बल दे सकते हैं?'],
    [src('Shiva Purana 7.1.4, Vayu’s arrival among the sages','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226640.html'),src('Shiva Purana 7.2.5, especially verses 1–8 and 34–37','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226677.html'),src('Shiva Purana 7.2.37, especially verses 6–19 and 57–59','https://www.wisdomlib.org/hinduism/book/shiva-purana-english/d/doc226709.html')],
    ['Vayaviya has two parts, each with its own chapter sequence. Locator 7.2.37 means part two, chapter 37. This overview gives no breath-retention or initiation instructions.','वायवीय संहिता के दो भाग हैं और प्रत्येक में अध्यायों का अपना क्रम है। संकेत 7.2.37 का अर्थ है दूसरा भाग, अध्याय 37। यह परिचय श्वास-रोध या दीक्षा के निर्देश नहीं देता।']
  ),
};

export const guideKeys=Object.keys(guideContent);
