import {READING_KEY,readReadingState,saveProgress,setPreference,setOnboarding,toggleBookmark,removeProgress,removeBookmark,restoreRemovedReadingItem,mostRecentProgress,resolveProgress} from './reading-state.js';
import {SHELF_KEY,readShelf} from './library-state.js';

const node=document.querySelector('#reading-data');
if(!node)throw Error('Reading data missing');
const data=JSON.parse(node.textContent);const $=id=>document.getElementById(id);const hi=data.lang==='hi';const say=(en,hindi)=>hi?hindi:en;
const storyMap=Object.fromEntries(data.stories.map(story=>[story.id,story]));
let snapshot=readReadingState(localStorage,data.storyKeys);
const volatilePreferences={};
let liveRegion;
function announce(message){if(!liveRegion){liveRegion=document.createElement('p');liveRegion.className='sr-only';liveRegion.setAttribute('role','status');liveRegion.setAttribute('aria-live','polite');document.body.append(liveRegion);}liveRegion.textContent='';requestAnimationFrame(()=>liveRegion.textContent=message);}
const route=(path)=>`${hi?'/hi':''}${path}`;
const title=story=>story?.title?.[data.lang]||story?.title?.en||'';
const book=story=>story?.book?.[data.lang]||story?.book?.en||'';
function refresh(){snapshot=readReadingState(localStorage,data.storyKeys);return snapshot;}
function effectiveState(state=snapshot.state){return {...state,preferences:{...state.preferences,...volatilePreferences}};}
function localizedCurrentUrl(language){const url=new URL(location.href);let path=url.pathname.replace(/^\/hi(?=\/|$)/,'')||'/';if(language==='hi')path=`/hi${path}`;return `${path}${url.search}${url.hash}`;}
const readerHash=value=>/^#(?:(?:block|scene)-[a-z0-9-]+|story-(?:reflection|source))$/.test(value)?value:'';
let requestedReaderHash=data.page==='reader'?readerHash(location.hash):'';
const resumeReaderNavigation=data.page==='reader'&&requestedReaderHash&&new URLSearchParams(location.search).get('from')==='resume';
// Preserve the requested resume target in memory, but remove the fragment until the
// exact within-paragraph scroll is applied. Otherwise a late native fragment jump can
// overwrite the saved ratio on slower production loads.
if(resumeReaderNavigation)history.replaceState(history.state,'',`${location.pathname}${location.search}`);
function readerLanguageUrl(language){const raw=localizedCurrentUrl(language);if(data.page!=='reader'||!requestedReaderHash)return raw;const url=new URL(raw,location.origin);url.hash=requestedReaderHash;return `${url.pathname}${url.search}${url.hash}`;}
function updateReaderLanguageLinks(){if(data.page!=='reader')return;for(const link of document.querySelectorAll('.reader-language a.language,[data-reader-language]')){const language=link.lang||link.dataset.readerLanguage;link.href=readerLanguageUrl(language);}}
function storyUrl(storyId,reader=false){return route(`/${reader?'read':'story'}/${storyId}/`);}
function sceneName(storyId,sceneId,language=data.lang){const full=data.story?.id===storyId?data.story:storyMap[storyId];const scene=full?.scenes?.find(item=>item.id===sceneId);return scene?.title?.[language]||scene?.title?.[data.lang]||scene?.title?.en||sceneId.replaceAll('-',' ');}
function safeReaderReturn(value){if(!value)return null;let url;try{url=new URL(value,location.origin);}catch{return null;}if(url.origin!==location.origin||!/^\/(?:hi\/)?read\/[a-z0-9-]+\/$/.test(url.pathname))return null;if(hi&&!url.pathname.startsWith('/hi/'))url.pathname=`/hi${url.pathname}`;if(!hi)url.pathname=url.pathname.replace(/^\/hi\//,'/');return `${url.pathname}${url.search}${url.hash}`;}

const characterBack=$('character-back'),readerReturn=safeReaderReturn(new URLSearchParams(location.search).get('from'));
if(characterBack&&readerReturn){characterBack.href=readerReturn;const label=characterBack.querySelector('span');if(label)label.textContent=say('Back to reading','पठन पर लौटें');}

for(const language of document.querySelectorAll('.language')){const code=language.lang||language.getAttribute('lang')||'en';language.href=data.page==='reader'?readerLanguageUrl(code):localizedCurrentUrl(code);language.addEventListener('click',()=>{if(data.page==='reader')language.href=readerLanguageUrl(code);try{setPreference(localStorage,data.storyKeys,'language',code);}catch{}});}
window.addEventListener('storage',event=>{if(event.key===READING_KEY||event.key===null){refresh();renderHomeContinue();renderDetailState();renderMyReading();}if(event.key===SHELF_KEY||event.key===null)renderSavedGuides();});

function renderHomeContinue(){const section=$('continue-reading');if(!section)return;const current=refresh();if(current.kind==='invalid'){section.hidden=true;return;}const recent=mostRecentProgress(current.state);const story=recent&&storyMap[recent.storyId];section.hidden=!story;if(!story)return;$('continue-title').textContent=title(story);$('continue-context').textContent=`${book(story)} · ${sceneName(story.id,recent.sceneId)}`;$('continue-link').href=`${storyUrl(story.id,true)}?from=resume#block-${recent.blockId}`;}
renderHomeContinue();

const filters={search:$('story-search'),epic:$('epic-filter'),age:$('age-filter'),value:$('value-filter'),duration:$('duration-filter')};
function filterLibrary(updateUrl=false){if(!filters.search)return;const query=filters.search.value.normalize('NFKD').toLocaleLowerCase().trim().slice(0,120);let count=0;for(const card of document.querySelectorAll('[data-story-card]')){const age=Number(card.dataset.age),duration=Number(card.dataset.duration);const ageMatch=!filters.age.value||(filters.age.value==='family'&&age<=7)||(filters.age.value==='independent'&&age===8)||(filters.age.value==='older'&&age>=9);const durationMatch=!filters.duration.value||(filters.duration.value==='short'&&duration<=6)||(filters.duration.value==='medium'&&duration>=7);const visible=(!query||card.dataset.search.normalize('NFKD').toLocaleLowerCase().includes(query))&&(!filters.epic.value||card.dataset.epic===filters.epic.value)&&ageMatch&&(!filters.value.value||card.dataset.values.split(' ').includes(filters.value.value))&&durationMatch;card.hidden=!visible;if(visible)count++;}$('story-count').textContent=hi?`${count} कथाएँ`:`${count} ${count===1?'story':'stories'}`;$('story-empty').hidden=count>0;if(updateUrl){const url=new URL(location.href);for(const [key,input] of Object.entries(filters)){const param=key==='search'?'q':key;if(input.value)url.searchParams.set(param,input.value);else url.searchParams.delete(param);}history.replaceState(history.state,'',`${url.pathname}${url.search}`);syncLanguageUrl(url);}}
function syncLanguageUrl(url){const language=document.querySelector('.language');if(!language)return;const target=new URL(language.href,location.href);for(const key of ['q','epic','age','value','duration','world']){const value=url.searchParams.get(key);if(value)target.searchParams.set(key,value);else target.searchParams.delete(key);}language.href=`${target.pathname}${target.search}`;}
if(filters.search){const params=new URLSearchParams(location.search);for(const [key,input] of Object.entries(filters)){const param=key==='search'?'q':key;const value=(params.get(param)||'').slice(0,120);if(input.tagName==='SELECT'&&![...input.options].some(option=>option.value===value))continue;input.value=value;input.addEventListener(input.tagName==='SELECT'?'change':'input',()=>filterLibrary(true));}if(['epic','age','value','duration'].some(key=>params.has(key)))$('advanced-filters').open=true;$('clear-filters').addEventListener('click',()=>{Object.values(filters).forEach(input=>input.value='');filterLibrary(true);filters.search.focus();});$('story-empty').querySelector('button').addEventListener('click',()=>{$('clear-filters').click();});filterLibrary();syncLanguageUrl(new URL(location.href));}

function firstBookmark(story){const scene=story.scenes[0],block=scene.blocks[0];return {storyId:story.id,sceneId:scene.id,blockId:block.id,language:data.lang,kind:'story',createdAt:Date.now()};}
function renderDetailState(){const button=document.querySelector('[data-save-story]');if(!button||!data.story)return;const current=refresh();const unreadable=current.kind==='invalid';button.disabled=unreadable;if(unreadable){button.querySelector('span').textContent=say('Saved data needs attention','सहेजे डेटा पर ध्यान दें');return;}const item=firstBookmark(data.story),saved=current.state.bookmarks.some(mark=>mark.storyId===item.storyId&&mark.sceneId===item.sceneId&&mark.blockId===item.blockId&&mark.language===item.language&&mark.kind==='story');button.setAttribute('aria-pressed',String(saved));button.querySelector('span').textContent=saved?say('Remove saved story','सहेजी कथा हटाएँ'):say('Save for later','बाद के लिए सहेजें');const progress=current.state.progress[data.story.id];const read=document.querySelector('[data-read-story]');if(progress&&read){read.href=`${storyUrl(data.story.id,true)}?from=resume#block-${progress.blockId}`;const label=[...read.childNodes].find(item=>item.nodeType===Node.TEXT_NODE);if(label)label.textContent=say('Resume story','कथा जारी रखें');}}
renderDetailState();
document.querySelector('[data-save-story]')?.addEventListener('click',()=>{try{toggleBookmark(localStorage,data.storyKeys,firstBookmark(data.story));renderDetailState();announce(say('Saved reading updated on this device.','इस डिवाइस पर सहेजा पठन अपडेट हुआ।'));}catch{renderDetailState();announce(say('Could not update saved reading. Nothing was overwritten.','सहेजा पठन अपडेट नहीं हुआ। कुछ भी बदला नहीं गया।'));}});

function openDialog(dialog,trigger){if(!dialog)return;dialog.dataset.returnFocus=trigger?.id||'';dialog.showModal();}
function applyReaderPreference(state){const reader=document.querySelector('.story-reader');if(!reader)return;reader.dataset.readerTheme=state.preferences.theme;reader.style.setProperty('--reader-size',`${state.preferences.textSize}px`);for(const button of document.querySelectorAll('[data-reader-theme]'))button.setAttribute('aria-pressed',String(button.dataset.readerTheme===state.preferences.theme));for(const button of document.querySelectorAll('[data-reader-size]'))button.setAttribute('aria-pressed',String(Number(button.dataset.readerSize)===state.preferences.textSize));}

if(data.page==='reader'){
 const reader=document.querySelector('.story-reader'),story=data.story,settingsDialog=$('reader-settings'),contextDialog=$('context-sheet'),settingsOpen=$('reader-settings-open');let currentBlock=story.scenes[0].blocks[0],currentScene=story.scenes[0],scrolled=false,restoring=true,saveTimer=0,suppressSavesUntil=0;
 function placeForReaderHash(hash){if(hash.startsWith('#scene-')){const scene=story.scenes.find(item=>item.id===hash.slice(7));return scene?{scene,block:scene.blocks[0]}:null;}if(hash.startsWith('#block-')){const blockId=hash.slice(7);for(const scene of story.scenes){const block=scene.blocks.find(item=>item.id===blockId);if(block)return {scene,block};}}return null;}
 function chooseRequestedPlace(hash){requestedReaderHash=readerHash(hash);const place=placeForReaderHash(requestedReaderHash);if(place){currentScene=place.scene;currentBlock=place.block;}suppressSavesUntil=performance.now()+1000;updateReaderLanguageLinks();renderBookmarkButton();}
 const languagePanel=document.createElement('div');languagePanel.className='reader-language-setting';const languageLabel=document.createElement('strong');languageLabel.textContent=say('Story language','कथा की भाषा');const languageLinks=document.createElement('div');languageLinks.className='segmented';for(const [code,label] of [['en','English'],['hi','हिन्दी']]){const link=document.createElement('a');link.href=readerLanguageUrl(code);link.lang=code;link.dataset.readerLanguage=code;link.textContent=label;if(code===data.lang)link.setAttribute('aria-current','page');link.addEventListener('click',()=>{link.href=readerLanguageUrl(code);try{setPreference(localStorage,data.storyKeys,'language',code);}catch{}});languageLinks.append(link);}languagePanel.append(languageLabel,languageLinks);settingsDialog.querySelector('.sheet-body').prepend(languagePanel);
 applyReaderPreference(effectiveState());
 updateReaderLanguageLinks();
 for(const link of document.querySelectorAll('.reader-contents a,.reader-journey a'))link.addEventListener('click',()=>{chooseRequestedPlace(new URL(link.href).hash);link.closest('details')?.removeAttribute('open');});
 addEventListener('hashchange',()=>chooseRequestedPlace(location.hash));
 if(snapshot.kind==='invalid')announce(say('Saved reading settings could not be read. This page is using safe defaults.','सहेजी पठन सेटिंग पढ़ी नहीं जा सकी। यह पृष्ठ सुरक्षित सामान्य रूप का उपयोग कर रहा है।'));
 settingsOpen.addEventListener('click',()=>openDialog(settingsDialog,settingsOpen));
 function changeComfortSetting(key,value){volatilePreferences[key]=value;applyReaderPreference(effectiveState());const status=$('reader-settings-status');try{const state=setPreference(localStorage,data.storyKeys,key,value);delete volatilePreferences[key];snapshot={kind:'ready',state};applyReaderPreference(effectiveState());status.textContent=say('Saved on this device.','इस डिवाइस पर सहेजा गया।');}catch{const message=say('Applied for this tab. This browser is not allowing the setting to be saved.','इस टैब के लिए लागू। ब्राउज़र इस सेटिंग को सहेजने की अनुमति नहीं दे रहा है।');status.textContent=message;announce(message);}}
 for(const button of document.querySelectorAll('[data-reader-theme]'))button.addEventListener('click',()=>changeComfortSetting('theme',button.dataset.readerTheme));
 for(const button of document.querySelectorAll('[data-reader-size]'))button.addEventListener('click',()=>changeComfortSetting('textSize',Number(button.dataset.readerSize)));
 function requestedAnchorIsCurrent(){if(!requestedReaderHash)return false;const target=document.getElementById(requestedReaderHash.slice(1));if(!target)return false;const rect=target.getBoundingClientRect();return rect.top<innerHeight-80&&rect.bottom>56;}
 function identifyPlace(){const targetY=88,nonReadingAnchor=requestedReaderHash==='#story-reflection'||requestedReaderHash==='#story-source';let found=null;for(const section of document.querySelectorAll('[data-scene-id]')){for(const block of section.querySelectorAll('[data-block-id]')){const rect=block.getBoundingClientRect();if(rect.top<=targetY+40)found={block,section,rect};}}if(!found)return;const requestedPlace=placeForReaderHash(requestedReaderHash),requestedCurrent=requestedPlace&&requestedAnchorIsCurrent();if(requestedCurrent){currentScene=requestedPlace.scene;currentBlock=requestedPlace.block;}else{currentScene=story.scenes.find(item=>item.id===found.section.dataset.sceneId)||currentScene;currentBlock=currentScene.blocks.find(item=>item.id===found.block.dataset.blockId)||currentBlock;}const requestedScene=requestedReaderHash.startsWith('#scene-')?requestedReaderHash.slice(7):null,journeyScene=requestedScene||currentScene.id;for(const link of document.querySelectorAll('[data-reader-scene]')){if(link.dataset.readerScene===journeyScene)link.setAttribute('aria-current','step');else link.removeAttribute('aria-current');}const ratio=requestedCurrent?0:Math.max(0,Math.min(1,(targetY-found.rect.top)/Math.max(1,found.rect.height)));if(scrolled&&!nonReadingAnchor&&performance.now()>=suppressSavesUntil){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{saveProgress(localStorage,data.storyKeys,{storyId:story.id,contentRevision:data.revision,language:data.lang,sceneId:currentScene.id,blockId:currentBlock.id,blockOffsetRatio:ratio,updatedAt:Date.now()});}catch{announce(say('Your place could not be saved. Reading can continue.','आपका स्थान सहेजा नहीं जा सका। पठन जारी रख सकते हैं।'));}},350);}if(requestedReaderHash&&!nonReadingAnchor&&performance.now()>=suppressSavesUntil&&!requestedAnchorIsCurrent())requestedReaderHash='';const nextHash=requestedReaderHash||`#block-${currentBlock.id}`;const max=document.documentElement.scrollHeight-innerHeight;const progress=max>0?Math.max(0,Math.min(1,scrollY/max)):0;$('reader-progress-bar').style.width=`${progress*100}%`;if(location.hash!==nextHash)history.replaceState(history.state,'',`${location.pathname}${location.search}${nextHash}`);updateReaderLanguageLinks();renderBookmarkButton();}
 let ticking=false;addEventListener('scroll',()=>{if(restoring)return;if(performance.now()>=suppressSavesUntil)scrolled=true;if(!ticking){requestAnimationFrame(()=>{identifyPlace();ticking=false;});ticking=true;}},{passive:true});
 const nextFrame=()=>new Promise(resolve=>requestAnimationFrame(resolve));
 // The illuminated book reflows after local fonts settle; keep restoration scrolls read-only
 // long enough that they cannot replace the stored within-paragraph ratio.
 async function restore(){if(document.readyState!=='complete')await new Promise(resolve=>addEventListener('load',resolve,{once:true}));if(document.fonts?.ready)await document.fonts.ready;await nextFrame();await nextFrame();const current=refresh();const anchor=current.kind==='invalid'?null:resolveProgress(current.state.progress[story.id],{...story,contentRevision:data.revision});const explicitTarget=requestedReaderHash&&document.getElementById(requestedReaderHash.slice(1));let target=explicitTarget,ratio=0;if(!target&&anchor){target=document.querySelector(`[data-block-id="${CSS.escape(anchor.blockId)}"]`);ratio=anchor.ratio;}else if(target&&requestedReaderHash.startsWith('#block-')&&new URLSearchParams(location.search).get('from')==='resume'&&anchor&&requestedReaderHash===`#block-${anchor.blockId}`&&!anchor.revisionChanged)ratio=anchor.ratio;if(!target){restoring=false;identifyPlace();return;}const targetY=88,rect=target.getBoundingClientRect();suppressSavesUntil=performance.now()+1800;scrollTo({top:Math.max(0,rect.top+scrollY+(rect.height*ratio)-targetY),behavior:'auto'});await nextFrame();await nextFrame();restoring=false;identifyPlace();if(anchor?.revisionChanged&&!explicitTarget)announce(say('This story was revised. Your place was restored to the nearest scene.','यह कथा संशोधित हुई है। आपका स्थान निकटतम दृश्य पर लौटाया गया है।'));}
 restore();
 function bookmarkRecord(){return {storyId:story.id,sceneId:currentScene.id,blockId:currentBlock.id,language:data.lang,kind:'place',createdAt:Date.now()};}
 function renderBookmarkButton(){const current=refresh();if(current.kind==='invalid'){ $('bookmark-place').disabled=true;return;}const marked=current.state.bookmarks.some(item=>item.storyId===story.id&&item.sceneId===currentScene.id&&item.blockId===currentBlock.id&&item.language===data.lang&&item.kind!=='story');$('bookmark-place').setAttribute('aria-pressed',String(marked));$('bookmark-place').querySelector('span').textContent=marked?say('Saved','सहेजा'):say('Save place','स्थान सहेजें');}
 $('bookmark-place').addEventListener('click',()=>{try{toggleBookmark(localStorage,data.storyKeys,bookmarkRecord());renderBookmarkButton();announce($('bookmark-place').getAttribute('aria-pressed')==='true'?say('Place saved on this device.','स्थान इस डिवाइस पर सहेजा गया।'):say('Bookmark removed.','बुकमार्क हटाया गया।'));}catch{announce(say('Bookmark could not be updated. Nothing was overwritten.','बुकमार्क अपडेट नहीं हुआ। कुछ भी बदला नहीं गया।'));}});renderBookmarkButton();
 for(const button of document.querySelectorAll('[data-glossary],[data-character]'))button.addEventListener('click',()=>{const glossaryId=button.dataset.glossary,characterId=button.dataset.character;if(glossaryId){const term=data.glossary[glossaryId];$('context-kind').textContent=say('Glossary','शब्दार्थ');$('context-title').textContent=term.term[data.lang]||term.term.en;$('context-copy').textContent=term.meaning[data.lang]||term.meaning.en;$('context-source').textContent=say('Context meaning for this library; not a complete doctrinal definition.','इस पुस्तकालय के प्रसंग का अर्थ; पूर्ण दार्शनिक परिभाषा नहीं।');$('context-link').hidden=true;}else{const character=data.characters[characterId],returnPath=`${location.pathname}${location.search}#block-${currentBlock.id}`;$('context-kind').textContent=character.kind==='deity'?say('Deity context','देव स्वरूप का प्रसंग'):say('Character context','पात्र का प्रसंग');$('context-title').textContent=character.name[data.lang]||character.name.en;$('context-copy').textContent=character.bio[data.lang]||character.bio.en;$('context-source').textContent=`${say('Source context','स्रोत प्रसंग')}: ${character.source}`;$('context-link').href=`${route(`/characters/${characterId}/`)}?from=${encodeURIComponent(returnPath)}`;$('context-link').hidden=false;}openDialog(contextDialog,button);});
 const pageTurnMotion=matchMedia('(prefers-reduced-motion: reduce)');
 const readerScenes=[...document.querySelectorAll('.reader-scene')];
 const reflectionTarget=$('story-reflection');
 function turnLeaf(target,hash,direction,trigger){
  requestedReaderHash=hash;
  history.pushState(history.state,'',`${location.pathname}${location.search}${hash}`);
  updateReaderLanguageLinks();
  const destination=target.querySelector('h2')||target;
  const settle=()=>{target.scrollIntoView({block:'start',behavior:'auto'});requestAnimationFrame(()=>{identifyPlace();destination.tabIndex=-1;destination.focus({preventScroll:true});});};
  if(pageTurnMotion.matches){settle();announce(say('Page turned.','पृष्ठ पलटा।'));return;}
  const column=document.querySelector('.reader-column'),rect=column.getBoundingClientRect(),chrome=document.querySelector('.reader-chrome')?.getBoundingClientRect();
  const veil=document.createElement('div');veil.className=`reader-page-turn-veil ${direction==='back'?'is-back':''}`;veil.setAttribute('aria-hidden','true');
  veil.style.setProperty('--leaf-left',`${Math.max(0,rect.left)}px`);
  veil.style.setProperty('--leaf-top',`${Math.max(chrome?.bottom||0,0)}px`);
  veil.style.setProperty('--leaf-width',`${Math.min(innerWidth-Math.max(0,rect.left),rect.width)}px`);
  veil.style.setProperty('--leaf-height',`${Math.max(180,innerHeight-Math.max(chrome?.bottom||0,0))}px`);
  document.body.append(veil);
  setTimeout(settle,220);
  veil.addEventListener('animationend',()=>{veil.remove();announce(say('Page turned.','पृष्ठ पलटा।'));},{once:true});
  setTimeout(()=>veil.remove(),700);
 }
 readerScenes.forEach((scene,index)=>{
  const nav=document.createElement('nav');nav.className='reader-page-nav';nav.setAttribute('aria-label',say('Turn the page','पृष्ठ पलटें'));
  if(index>0){const previous=document.createElement('button');previous.type='button';previous.className='leaf-turn leaf-turn-back';previous.innerHTML=`<span aria-hidden="true">←</span><span>${say('Previous folio','पिछला पृष्ठ')}</span>`;previous.addEventListener('click',()=>turnLeaf(readerScenes[index-1],`#scene-${readerScenes[index-1].dataset.sceneId}`,'back',previous));nav.append(previous);}
  const target=index<readerScenes.length-1?readerScenes[index+1]:reflectionTarget;
  if(target){const next=document.createElement('button');next.type='button';next.className='leaf-turn leaf-turn-forward';next.innerHTML=`<span>${index<readerScenes.length-1?say('Turn the page','पृष्ठ पलटें'):say('Open reflection','मनन खोलें')}</span><span aria-hidden="true">→</span>`;const hash=index<readerScenes.length-1?`#scene-${readerScenes[index+1].dataset.sceneId}`:'#story-reflection';next.addEventListener('click',()=>turnLeaf(target,hash,'forward',next));nav.append(next);}
  scene.append(nav);
 });
}

for(const dialog of document.querySelectorAll('.reading-sheet'))dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});

const preferenceDialog=$('reading-preferences');
for(const button of document.querySelectorAll('.preference-open'))button.addEventListener('click',()=>openDialog(preferenceDialog,button));
if($('preference-form'))$('preference-form').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.currentTarget),language=form.get('language'),textSize=Number(form.get('textSize')),interests=form.getAll('interests');try{setPreference(localStorage,data.storyKeys,'language',language);setPreference(localStorage,data.storyKeys,'textSize',textSize);setPreference(localStorage,data.storyKeys,'interests',interests);setOnboarding(localStorage,data.storyKeys,'complete');$('preference-status').textContent=say('Preferences saved on this device.','पसंद इस डिवाइस पर सहेजी गई।');setTimeout(()=>location.assign(localizedCurrentUrl(language)),180);}catch{$('preference-status').textContent=say('Preferences could not be saved. You can close this and keep browsing.','पसंद सहेजी नहीं जा सकी। इसे बंद करके आगे देख सकते हैं।');}});
$('skip-preferences')?.addEventListener('click',()=>{try{setOnboarding(localStorage,data.storyKeys,'skipped');}catch{}preferenceDialog.close();});

function makeReadingRow(item,kind){const story=storyMap[item.storyId];if(!story)return null;const row=document.createElement('article');row.className='reading-row';const copy=document.createElement('div');const heading=document.createElement('h3');heading.textContent=title(story);const scene=story.scenes?.find(value=>value.id===item.sceneId),block=scene?.blocks?.find(value=>value.id===item.blockId),blockIndex=Math.max(0,scene?.blocks?.findIndex(value=>value.id===item.blockId)??0);const savedStory=kind==='bookmark'&&item.kind==='story';const kindLabel=kind==='progress'?say('Reading place','पठन स्थान'):savedStory?say('Saved story','सहेजी कथा'):say('Reading place','पठन स्थान');const details=document.createElement('p');details.className='reading-row-meta';details.textContent=`${kindLabel} · ${book(story)} · ${sceneName(item.storyId,item.sceneId)}${savedStory?'':` · ${say('Passage','अनुच्छेद')} ${blockIndex+1}`} · ${item.language==='hi'?'हिन्दी':'English'}`;const excerpt=document.createElement('p');excerpt.className='reading-row-excerpt';excerpt.lang=item.language;const source=savedStory?story.dek:block?.text;excerpt.textContent=source?.[item.language]||source?.[data.lang]||source?.en||'';copy.append(heading,details,excerpt);const actions=document.createElement('div');const open=document.createElement('a');open.className='button';const prefix=item.language==='hi'?'/hi':'';open.href=`${prefix}/read/${item.storyId}/?from=${kind==='progress'?'resume':'bookmark'}#block-${item.blockId}`;open.textContent=kind==='progress'?say('Resume','जारी रखें'):say('Open','खोलें');const remove=document.createElement('button');remove.type='button';remove.textContent=say('Remove','हटाएँ');remove.addEventListener('click',()=>removeReadingItem(item,kind));actions.append(open,remove);row.append(copy,actions);return row;}
let undoItem=null,undoTimer=0;
function removeReadingItem(item,kind){const current=refresh();if(current.kind==='invalid')return;try{undoItem={type:kind==='progress'?'progress':'bookmark',item:structuredClone(item)};if(kind==='progress')removeProgress(localStorage,data.storyKeys,item.storyId);else removeBookmark(localStorage,data.storyKeys,item);renderMyReading();const toast=$('reading-undo');toast.querySelector('span').textContent=say('Saved reading removed.','सहेजा पठन हटाया गया।');toast.hidden=false;clearTimeout(undoTimer);undoTimer=setTimeout(()=>{toast.hidden=true;undoItem=null;},5000);}catch{undoItem=null;announce(say('Could not remove saved reading.','सहेजा पठन हटाया नहीं जा सका।'));}}
function renderMyReading(){if(!$('reading-empty'))return;const current=refresh();const warning=$('reading-storage-warning');warning.hidden=current.kind!=='invalid';if(current.kind==='invalid'){$('resume-section').hidden=true;$('bookmark-section').hidden=true;$('reading-empty').hidden=true;return;}const progress=Object.values(current.state.progress).sort((a,b)=>b.updatedAt-a.updatedAt),bookmarks=current.state.bookmarks;for(const [sectionId,listId,items,kind] of [['resume-section','resume-list',progress,'progress'],['bookmark-section','bookmark-list',bookmarks,'bookmark']]){const section=$(sectionId),list=$(listId);list.replaceChildren();for(const item of items){const row=makeReadingRow(item,kind);if(row)list.append(row);}section.hidden=!list.children.length;}$('reading-empty').hidden=progress.length>0||bookmarks.length>0;}
function renderSavedGuides(){const root=$('saved-guide-list');if(!root)return;const guides=data.sourceGuides||[],allowed=guides.map(guide=>guide.id),state=readShelf(localStorage,allowed);root.replaceChildren();$('saved-guide-warning').hidden=state.kind!=='invalid';$('saved-guide-empty').hidden=state.kind==='invalid'||state.items.length>0;$('manage-saved-guides').hidden=state.kind!=='invalid'&&state.items.length===0;if(state.kind==='invalid')return;for(const id of state.items){const guide=guides.find(item=>item.id===id);if(!guide)continue;const row=document.createElement('article');row.className='reading-row saved-guide-row';const copy=document.createElement('div');const heading=document.createElement('h3');heading.textContent=guide.title;const detail=document.createElement('p');detail.className='reading-row-meta';detail.textContent=`${say('Source guide','स्रोत-मार्गदर्शिका')} · ${guide.collection}`;copy.append(heading,detail);const actions=document.createElement('div');const open=document.createElement('a');open.className='button';open.href=guide.href;open.textContent=say('Open guide','मार्गदर्शिका खोलें');actions.append(open);row.append(copy,actions);root.append(row);}}
renderMyReading();renderSavedGuides();
$('repair-reading')?.addEventListener('click',()=>{try{localStorage.removeItem(READING_KEY);renderMyReading();announce(say('Unreadable reading data removed.','अपठनीय पठन डेटा हटाया गया।'));}catch{announce(say('Unreadable data could not be removed.','अपठनीय डेटा हटाया नहीं जा सका।'));}});
$('reading-undo')?.querySelector('button')?.addEventListener('click',()=>{if(!undoItem)return;try{restoreRemovedReadingItem(localStorage,data.storyKeys,undoItem);undoItem=null;$('reading-undo').hidden=true;renderMyReading();announce(say('Saved reading restored without changing newer activity.','नया पठन बदले बिना सहेजा पठन वापस लाया गया।'));}catch{announce(say('Saved reading could not be restored.','सहेजा पठन वापस नहीं लाया जा सका।'));}});

if($('daily-date'))$('daily-date').textContent=new Intl.DateTimeFormat(data.lang==='hi'?'hi-IN':'en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());
